import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import javax.inject.Inject

plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeCompiler)
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}

// Resolves the dictionary database + sidecar directory generated by :tools:dictgen.
val dictionary: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
    attributes {
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category::class.java, "okonomi-dictionary"))
    }
}

dependencies {
    implementation(project(":shared"))

    implementation(libs.androidx.activity.compose)

    implementation(libs.compose.uiToolingPreview)
    debugImplementation(libs.compose.uiTooling)

    dictionary(project(":tools:dictgen"))
}

android {
    namespace = "cc.hosaka.okonomi"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "cc.hosaka.okonomi"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }
}

/**
 * Copies the generated dictionary files into a directory AGP wires up as
 * generated assets, so the APK carries assets/okonomi.db and
 * assets/okonomi.db.version.
 */
abstract class SyncDictionaryAssets : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val dictionaryDir: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Inject
    abstract val fileSystemOperations: FileSystemOperations

    @TaskAction
    fun sync() {
        fileSystemOperations.sync {
            from(dictionaryDir)
            into(outputDir)
        }
        // Guard against silent name drift between dictgen and the runtime
        // asset constants: a wrong or missing file would otherwise only
        // show up as a vanished Settings row at runtime.
        val expected = listOf("okonomi.db", "okonomi.db.version")
        val synced = outputDir.get().asFile.listFiles().orEmpty().map { it.name }.sorted()
        if (synced != expected) {
            throw GradleException(
                "Dictionary asset mismatch: expected exactly $expected in the synced assets " +
                    "but found $synced. The dictgen output names and the app's asset name " +
                    "constants must stay in lockstep.",
            )
        }
    }
}

androidComponents {
    onVariants { variant ->
        val variantName = variant.name.replaceFirstChar { it.uppercase() }
        val syncTask = tasks.register<SyncDictionaryAssets>("sync${variantName}DictionaryAssets") {
            dictionaryDir.from(dictionary)
        }
        // Without the assets source the APK would silently ship without the
        // dictionary, so fail the build instead.
        val assets = variant.sources.assets
            ?: error("assets source unavailable for ${variant.name}; the dictionary cannot be packaged")
        assets.addGeneratedSourceDirectory(syncTask, SyncDictionaryAssets::outputDir)
    }
}
