package cc.hosaka.okonomi.db

import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import app.cash.sqldelight.ExecutableQuery
import app.cash.sqldelight.db.QueryResult
import app.cash.sqldelight.db.SqlDriver
import com.eygraber.sqldelight.androidx.driver.AndroidxSqliteConfiguration
import com.eygraber.sqldelight.androidx.driver.AndroidxSqliteDatabaseType
import com.eygraber.sqldelight.androidx.driver.AndroidxSqliteDriver
import com.eygraber.sqldelight.androidx.driver.SqliteJournalMode
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock

/**
 * File name of the dictionary database generated by :tools:dictgen and
 * bundled with the app (Android asset, iOS bundle resource). The Gradle
 * asset wiring copies the dictgen output directory verbatim, so these
 * names match the generated files by construction.
 */
const val DICTIONARY_DB_NAME = "okonomi.db"

/**
 * Sidecar bundled next to [DICTIONARY_DB_NAME], content
 * `<jmdict_date>:<schema_version>:<data_format_version>`. Provisioning
 * compares the bundled sidecar with the persisted one verbatim, so any
 * component that moves forces a re-copy — the data format version is
 * what catches a change the schema cannot see, such as a reworked
 * ranking formula over unchanged columns.
 */
const val DICTIONARY_SIDECAR_NAME = "$DICTIONARY_DB_NAME.version"

private val provisioningMutex = Mutex()

/**
 * Ensures the bundled dictionary database exists as a plain file in the
 * app's private storage and returns its absolute path. Copies stream the
 * bundled asset to a temp file and atomically rename it, so an
 * interrupted copy is never observable as the database; the sidecar is
 * persisted last and re-checked on every call. Runs off the main thread.
 * Failures throw and are expected to surface as a non-crashing load
 * failure at the call site.
 *
 * Single-flight: concurrent callers are serialized on one mutex so two
 * provisioning runs can never interleave their delete/copy/rename steps.
 */
suspend fun provisionDictionary(): String = provisionSingleFlight { provisionDictionaryUnlocked() }

internal suspend fun provisionSingleFlight(provision: suspend () -> String): String =
    provisioningMutex.withLock { provision() }

/**
 * Platform provisioning body. Never call directly: only
 * [provisionDictionary] may run it, under the single-flight mutex.
 */
internal expect suspend fun provisionDictionaryUnlocked(): String

/**
 * Deletes the persisted database copy and its sidecar so the next
 * [provisionDictionary] call re-copies from the bundled asset. Used to
 * self-heal when an already-provisioned database turns out to be
 * unreadable (corrupt copy with a matching sidecar).
 */
expect fun resetDictionaryProvisioning()

/**
 * An open handle on the read-only dictionary database. The app never
 * executes writes against [db]: only query use is exposed to features.
 */
class DictionaryDatabase internal constructor(
    val db: OkonomiDb,
    private val driver: SqlDriver,
) : AutoCloseable {
    override fun close() {
        driver.close()
    }
}

/**
 * Opens the provisioned dictionary file with the bundled SQLite driver.
 * The shipped file carries `PRAGMA user_version` equal to the schema
 * version, so the driver skips schema creation and migration. Journal
 * mode Delete keeps a read-only database free of WAL sidecar files.
 */
fun openOkonomiDb(path: String): DictionaryDatabase {
    val driver = AndroidxSqliteDriver(
        driver = BundledSQLiteDriver(),
        databaseType = AndroidxSqliteDatabaseType.File(path),
        schema = OkonomiDb.Schema,
        configuration = AndroidxSqliteConfiguration(
            journalMode = SqliteJournalMode.Delete,
        ),
    )
    return DictionaryDatabase(OkonomiDb(driver), driver)
}

/**
 * The dictionary version information shown in Settings.
 */
data class DictionaryInfo(
    val jmdictDate: String,
    val entryCount: Long,
)

/**
 * Reads the version metadata off the shared dictionary handle,
 * provisioning and opening it on first use. When the provisioned file
 * cannot be opened or queried, the memoized handle is dropped and the
 * persisted copy wiped before rethrowing, so the next run re-copies a
 * fresh one.
 */
suspend fun loadDictionaryInfo(): DictionaryInfo = loadDictionaryInfo(
    dictionary = ::dictionary,
    reset = {
        // A throwing invalidate must never mask the original failure
        // or skip the file reset.
        runCatching { invalidateDictionary() }
        resetDictionaryProvisioning()
    },
)

internal suspend fun loadDictionaryInfo(
    dictionary: suspend () -> DictionaryDatabase,
    reset: suspend () -> Unit,
): DictionaryInfo = try {
    val database = dictionary()
    DictionaryInfo(
        jmdictDate = database.db.metadataQueries.metadataValue("jmdict_date").awaitOneOrNull() ?: "unknown",
        entryCount = database.db.entryQueries.entryCount().awaitOne(),
    )
} catch (e: CancellationException) {
    throw e
} catch (e: Exception) {
    // The reset is a best-effort self-heal; if it fails too, the
    // caller still needs to see what actually went wrong.
    try {
        reset()
    } catch (resetFailure: CancellationException) {
        throw resetFailure
    } catch (resetFailure: Exception) {
        e.addSuppressed(resetFailure)
    }
    throw e
}

/**
 * Awaits the single row of an async-codegen query. Local stand-ins for
 * sqldelight's async-extensions artifact, which is intentionally not a
 * dependency.
 */
internal suspend fun <T : Any> ExecutableQuery<T>.awaitOne(): T =
    checkNotNull(awaitOneOrNull()) { "Query returned no rows: $this" }

/**
 * Awaits every row of an async-codegen query into a list, following the
 * same synchronous/asynchronous cursor split as [awaitOneOrNull].
 */
internal suspend fun <T : Any> ExecutableQuery<T>.awaitList(): List<T> = execute { cursor ->
    when (val first = cursor.next()) {
        is QueryResult.AsyncValue -> QueryResult.AsyncValue {
            buildList {
                var hasNext = first.await()
                while (hasNext) {
                    // A large result set is a long loop: a superseded
                    // keystroke must be able to stop it.
                    currentCoroutineContext().ensureActive()
                    add(mapper(cursor))
                    hasNext = cursor.next().await()
                }
            }
        }

        // The synchronous branch runs inside a non-suspending mapper,
        // so there is no coroutine context to check here; only test
        // drivers take it, and callers check around the call instead.
        is QueryResult.Value -> {
            val rows = mutableListOf<T>()
            var hasNext = first.value
            while (hasNext) {
                rows.add(mapper(cursor))
                hasNext = cursor.next().value
            }
            QueryResult.Value<List<T>>(rows)
        }
    }
}.await()

internal suspend fun <T : Any> ExecutableQuery<T>.awaitOneOrNull(): T? = execute { cursor ->
    // A synchronous driver closes the cursor as soon as the mapper
    // returns, so its rows must be consumed inside the mapper; only a
    // truly asynchronous cursor defers into an AsyncValue.
    when (val first = cursor.next()) {
        is QueryResult.AsyncValue -> QueryResult.AsyncValue {
            if (!first.await()) return@AsyncValue null
            val value = mapper(cursor)
            check(!cursor.next().await()) { "Query returned more than one row: $this" }
            value
        }

        is QueryResult.Value -> {
            if (!first.value) {
                QueryResult.Value(null)
            } else {
                val value = mapper(cursor)
                check(!cursor.next().value) { "Query returned more than one row: $this" }
                QueryResult.Value<T?>(value)
            }
        }
    }
}.await()
