/*
 * Copyright (C) 2023-2026  Yomitan Authors
 * Copyright (C) 2020-2022  Yomichan Authors
 * Copyright (C) 2026  Okonomi Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Ported to Kotlin from Yomitan's test/language/japanese-transforms.test.js
 * at commit 77e200428902abf4fa48284df92da7af3dcb4162 (2026-08-18):
 * the full deinflection test corpus (33 categories, 1406 rows).
 * Machine-generated from the upstream test data (conversion script not
 * committed).
 */
package cc.hosaka.okonomi.deinflect

data class CorpusRow(
    val term: String,
    val source: String,
    val rule: String?,
    val reasons: List<String>?,
)

class CorpusCategory(
    val category: String,
    val valid: Boolean,
    val rows: List<CorpusRow>,
)

private fun category0Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("愛しい", "愛しい", "adj-i", listOf()),
    CorpusRow("愛しい", "愛しそう", "adj-i", listOf("-そう")),
    CorpusRow("愛しい", "愛しさう", "adj-i", listOf("-そう")),
    CorpusRow("愛しい", "愛しすぎる", "adj-i", listOf("-すぎる")),
    CorpusRow("愛しい", "愛し過ぎる", "adj-i", listOf("-過ぎる")),
    CorpusRow("愛しい", "愛しかったら", "adj-i", listOf("-たら")),
    CorpusRow("愛しい", "愛しかったり", "adj-i", listOf("-たり")),
    CorpusRow("愛しい", "愛しくて", "adj-i", listOf("-て")),
    CorpusRow("愛しい", "愛しく", "adj-i", listOf("-く")),
    CorpusRow("愛しい", "愛しくない", "adj-i", listOf("negative")),
    CorpusRow("愛しい", "愛しさ", "adj-i", listOf("-さ")),
    CorpusRow("愛しい", "愛しかった", "adj-i", listOf("-た")),
    CorpusRow("愛しい", "愛しくありません", "adj-i", listOf("-ます", "negative")),
    CorpusRow("愛しい", "愛しくありませんでした", "adj-i", listOf("-ます", "negative", "-た")),
    CorpusRow("愛しい", "愛しくありませんかった", "adj-i", listOf("-ます", "negative", "-た")),
    CorpusRow("愛しい", "愛しき", "adj-i", listOf("-き")),
    CorpusRow("愛しい", "愛しげ", "adj-i", listOf("-げ")),
    CorpusRow("愛しい", "愛し気", "adj-i", listOf("-げ")),
    CorpusRow("愛しい", "愛しがる", "adj-i", listOf("-がる")),
    CorpusRow("愛しい", "愛しかろう", "adj-i", listOf("volitional")),
    CorpusRow("愛しい", "愛しからう", "adj-i", listOf("volitional")),
)

private fun category0(): CorpusCategory = CorpusCategory(
    category = "adjectives",
    valid = true,
    rows = category0Chunk0(),
)

private fun category1Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("食べる", "食べる", "v1", listOf()),
    CorpusRow("食べる", "食べます", "v1", listOf("-ます")),
    CorpusRow("食べる", "食べた", "v1", listOf("-た")),
    CorpusRow("食べる", "食べました", "v1", listOf("-ます", "-た")),
    CorpusRow("食べる", "食べて", "v1", listOf("-て")),
    CorpusRow("食べる", "食べられる", "v1", listOf("potential or passive")),
    CorpusRow("食べる", "食べられる", "v1", listOf("potential or passive")),
    CorpusRow("食べる", "食べさせる", "v1", listOf("causative")),
    CorpusRow("食べる", "食べさす", "v1", listOf("short causative")),
    CorpusRow("食べる", "食べさします", "v1", listOf("short causative", "-ます")),
    CorpusRow("食べる", "食べさせられる", "v1", listOf("causative", "potential or passive")),
    CorpusRow("食べる", "食べろ", "v1", listOf("imperative")),
    CorpusRow("食べる", "食べない", "v1", listOf("negative")),
    CorpusRow("食べる", "食べません", "v1", listOf("-ます", "negative")),
    CorpusRow("食べる", "食べなかった", "v1", listOf("negative", "-た")),
    CorpusRow("食べる", "食べませんでした", "v1", listOf("-ます", "negative", "-た")),
    CorpusRow("食べる", "食べなくて", "v1", listOf("negative", "-て")),
    CorpusRow("食べる", "食べられない", "v1", listOf("potential or passive", "negative")),
    CorpusRow("食べる", "食べられない", "v1", listOf("potential or passive", "negative")),
    CorpusRow("食べる", "食べさせない", "v1", listOf("causative", "negative")),
    CorpusRow("食べる", "食べささない", "v1", listOf("short causative", "negative")),
    CorpusRow("食べる", "食べさせられない", "v1", listOf("causative", "potential or passive", "negative")),
    CorpusRow("食べる", "食べまして", "v1", listOf("-ます", "-て")),
    CorpusRow("食べる", "食べれば", "v1", listOf("-ば")),
    CorpusRow("食べる", "食べりゃ", "v1", listOf("-ば", "-ゃ")),
    CorpusRow("食べる", "食べちゃ", "v1", listOf("-ちゃ")),
    CorpusRow("食べる", "食べちゃう", "v1", listOf("-ちゃう")),
    CorpusRow("食べる", "食べちまう", "v1", listOf("-ちまう")),
    CorpusRow("食べる", "食べなさい", "v1", listOf("-なさい")),
    CorpusRow("食べる", "食べそう", "v1", listOf("-そう")),
    CorpusRow("食べる", "食べさう", "v1", listOf("-そう")),
    CorpusRow("食べる", "食べすぎる", "v1", listOf("-すぎる")),
    CorpusRow("食べる", "食べ過ぎる", "v1", listOf("-過ぎる")),
    CorpusRow("食べる", "食べたい", "v1", listOf("-たい")),
    CorpusRow("食べる", "食べたがる", "v1", listOf("-たい", "-がる")),
    CorpusRow("食べる", "食べたら", "v1", listOf("-たら")),
    CorpusRow("食べる", "食べたり", "v1", listOf("-たり")),
    CorpusRow("食べる", "食べず", "v1", listOf("-ず")),
    CorpusRow("食べる", "食べぬ", "v1", listOf("-ぬ")),
    CorpusRow("食べる", "食べん", "v1", listOf("-ん")),
    CorpusRow("食べる", "食べんかった", "v1", listOf("-ん", "-た")),
    CorpusRow("食べる", "食べんばかり", "v1", listOf("-んばかり")),
    CorpusRow("食べる", "食べんとする", "v1", listOf("-んとする")),
    CorpusRow("食べる", "食べざる", "v1", listOf("-ざる")),
    CorpusRow("食べる", "食べねば", "v1", listOf("-ねば")),
    CorpusRow("食べる", "食べにゃ", "v1", listOf("-ねば", "-ゃ")),
    CorpusRow("食べる", "食べ", "v1d", listOf("continuative")),
    CorpusRow("食べる", "食べましょう", "v1", listOf("-ます", "volitional")),
    CorpusRow("食べる", "食べませう", "v1", listOf("-ます", "volitional")),
    CorpusRow("食べる", "食べましょっか", "v1", listOf("-ます", "volitional slang")),
)

private fun category1Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("食べる", "食べよう", "v1", listOf("volitional")),
    CorpusRow("食べる", "食べやう", "v1", listOf("volitional")),
    CorpusRow("食べる", "食べよっか", "v1", listOf("volitional slang")),
    CorpusRow("食べる", "食べるまい", "v1", listOf("-まい")),
    CorpusRow("食べる", "食べまい", "v1", listOf("-まい")),
    CorpusRow("食べる", "食べておく", "v1", listOf("-て", "-おく")),
    CorpusRow("食べる", "食べとく", "v1", listOf("-て", "-おく")),
    CorpusRow("食べる", "食べないでおく", "v1", listOf("negative", "-おく")),
    CorpusRow("食べる", "食べないどく", "v1", listOf("negative", "-おく")),
    CorpusRow("食べる", "食べている", "v1", listOf("-て", "-いる")),
    CorpusRow("食べる", "食べてゐる", "v1", listOf("-て", "-いる")),
    CorpusRow("食べる", "食べておる", "v1", listOf("-て", "-いる")),
    CorpusRow("食べる", "食べてる", "v1", listOf("-て", "-いる")),
    CorpusRow("食べる", "食べとる", "v1", listOf("-て", "-いる")),
    CorpusRow("食べる", "食べてしまう", "v1", listOf("-て", "-しまう")),
    CorpusRow("食べる", "食べやがる", "v1", listOf("-やがる")),
    CorpusRow("食べる", "食べやがって", "v1", listOf("-やがる", "-て")),
    CorpusRow("食べる", "食べやがった", "v1", listOf("-やがる", "-た")),
    CorpusRow("食べる", "食べやがれ", "v1", listOf("-やがる", "imperative")),
)

private fun category1(): CorpusCategory = CorpusCategory(
    category = "ichidan verbs",
    valid = true,
    rows = category1Chunk0() + category1Chunk1(),
)

private fun category2Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("買う", "買う", "v5", listOf()),
    CorpusRow("買う", "買います", "v5", listOf("-ます")),
    CorpusRow("買う", "買った", "v5", listOf("-た")),
    CorpusRow("買う", "買いました", "v5", listOf("-ます", "-た")),
    CorpusRow("買う", "買って", "v5", listOf("-て")),
    CorpusRow("買う", "買える", "v5", listOf("potential")),
    CorpusRow("買う", "買われる", "v5", listOf("passive")),
    CorpusRow("買う", "買わせる", "v5", listOf("causative")),
    CorpusRow("買う", "買わす", "v5", listOf("short causative")),
    CorpusRow("買う", "買わします", "v5", listOf("short causative", "-ます")),
    CorpusRow("買う", "買わせられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("買う", "買え", "v5", listOf("imperative")),
    CorpusRow("買う", "買わない", "v5", listOf("negative")),
    CorpusRow("買う", "買いません", "v5", listOf("-ます", "negative")),
    CorpusRow("買う", "買わなかった", "v5", listOf("negative", "-た")),
    CorpusRow("買う", "買いませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("買う", "買わなくて", "v5", listOf("negative", "-て")),
    CorpusRow("買う", "買えない", "v5", listOf("potential", "negative")),
    CorpusRow("買う", "買われない", "v5", listOf("passive", "negative")),
    CorpusRow("買う", "買わせない", "v5", listOf("causative", "negative")),
    CorpusRow("買う", "買わさない", "v5", listOf("short causative", "negative")),
    CorpusRow("買う", "買わせられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("買う", "買いまして", "v5", listOf("-ます", "-て")),
    CorpusRow("買う", "買えば", "v5", listOf("-ば")),
    CorpusRow("買う", "買や", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("買う", "買っちゃ", "v5", listOf("-ちゃ")),
    CorpusRow("買う", "買っちゃう", "v5", listOf("-ちゃう")),
    CorpusRow("買う", "買っちまう", "v5", listOf("-ちまう")),
    CorpusRow("買う", "買いなさい", "v5", listOf("-なさい")),
    CorpusRow("買う", "買いそう", "v5", listOf("-そう")),
    CorpusRow("買う", "買ひさう", "v5", listOf("-そう")),
    CorpusRow("買う", "買いすぎる", "v5", listOf("-すぎる")),
    CorpusRow("買う", "買い過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("買う", "買いたい", "v5", listOf("-たい")),
    CorpusRow("買う", "買いたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("買う", "買ったら", "v5", listOf("-たら")),
    CorpusRow("買う", "買ったり", "v5", listOf("-たり")),
    CorpusRow("買う", "買わず", "v5", listOf("-ず")),
    CorpusRow("買う", "買わぬ", "v5", listOf("-ぬ")),
    CorpusRow("買う", "買わん", "v5", listOf("-ん")),
    CorpusRow("買う", "買わんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("買う", "買わんばかり", "v5", listOf("-んばかり")),
    CorpusRow("買う", "買わんとする", "v5", listOf("-んとする")),
    CorpusRow("買う", "買わざる", "v5", listOf("-ざる")),
    CorpusRow("買う", "買わねば", "v5", listOf("-ねば")),
    CorpusRow("買う", "買わにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("買う", "買い", "v5", listOf("continuative")),
    CorpusRow("買う", "買いましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("買う", "買いませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("買う", "買いましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category2Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("買う", "買おう", "v5", listOf("volitional")),
    CorpusRow("買う", "買はう", "v5", listOf("volitional")),
    CorpusRow("買う", "買おっか", "v5", listOf("volitional slang")),
    CorpusRow("買う", "買うまい", "v5", listOf("-まい")),
    CorpusRow("買う", "買わされる", "v5", listOf("short causative", "passive")),
    CorpusRow("買う", "買っておく", "v5", listOf("-て", "-おく")),
    CorpusRow("買う", "買っとく", "v5", listOf("-て", "-おく")),
    CorpusRow("買う", "買わないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("買う", "買わないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("買う", "買っている", "v5", listOf("-て", "-いる")),
    CorpusRow("買う", "買ってゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("買う", "買っておる", "v5", listOf("-て", "-いる")),
    CorpusRow("買う", "買ってる", "v5", listOf("-て", "-いる")),
    CorpusRow("買う", "買っとる", "v5", listOf("-て", "-いる")),
    CorpusRow("買う", "買ってしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("買う", "買いやがる", "v5", listOf("-やがる")),
    CorpusRow("買う", "買いやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("買う", "買いやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("買う", "買いやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("買う", "買いますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("買う", "買いましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("買う", "買いますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("買う", "買いませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category2(): CorpusCategory = CorpusCategory(
    category = "-う verbs",
    valid = true,
    rows = category2Chunk0() + category2Chunk1(),
)

private fun category3Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("行く", "行く", "v5", listOf()),
    CorpusRow("行く", "行きます", "v5", listOf("-ます")),
    CorpusRow("行く", "行った", "v5", listOf("-た")),
    CorpusRow("行く", "行きました", "v5", listOf("-ます", "-た")),
    CorpusRow("行く", "行って", "v5", listOf("-て")),
    CorpusRow("行く", "行ける", "v5", listOf("potential")),
    CorpusRow("行く", "行かれる", "v5", listOf("passive")),
    CorpusRow("行く", "行かせる", "v5", listOf("causative")),
    CorpusRow("行く", "行かす", "v5", listOf("short causative")),
    CorpusRow("行く", "行かします", "v5", listOf("short causative", "-ます")),
    CorpusRow("行く", "行かせられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("行く", "行け", "v5", listOf("imperative")),
    CorpusRow("行く", "行かない", "v5", listOf("negative")),
    CorpusRow("行く", "行きません", "v5", listOf("-ます", "negative")),
    CorpusRow("行く", "行かなかった", "v5", listOf("negative", "-た")),
    CorpusRow("行く", "行きませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("行く", "行かなくて", "v5", listOf("negative", "-て")),
    CorpusRow("行く", "行けない", "v5", listOf("potential", "negative")),
    CorpusRow("行く", "行かれない", "v5", listOf("passive", "negative")),
    CorpusRow("行く", "行かせない", "v5", listOf("causative", "negative")),
    CorpusRow("行く", "行かさない", "v5", listOf("short causative", "negative")),
    CorpusRow("行く", "行かせられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("行く", "行きまして", "v5", listOf("-ます", "-て")),
    CorpusRow("行く", "行けば", "v5", listOf("-ば")),
    CorpusRow("行く", "行きゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("行く", "行っちゃ", "v5", listOf("-ちゃ")),
    CorpusRow("行く", "行っちゃう", "v5", listOf("-ちゃう")),
    CorpusRow("行く", "行っちまう", "v5", listOf("-ちまう")),
    CorpusRow("行く", "行きなさい", "v5", listOf("-なさい")),
    CorpusRow("行く", "行きそう", "v5", listOf("-そう")),
    CorpusRow("行く", "行きさう", "v5", listOf("-そう")),
    CorpusRow("行く", "行きすぎる", "v5", listOf("-すぎる")),
    CorpusRow("行く", "行き過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("行く", "行きたい", "v5", listOf("-たい")),
    CorpusRow("行く", "行きたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("行く", "行いたら", "v5", listOf("-たら")),
    CorpusRow("行く", "行いたり", "v5", listOf("-たり")),
    CorpusRow("行く", "行かず", "v5", listOf("-ず")),
    CorpusRow("行く", "行かぬ", "v5", listOf("-ぬ")),
    CorpusRow("行く", "行かん", "v5", listOf("-ん")),
    CorpusRow("行く", "行かんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("行く", "行かんばかり", "v5", listOf("-んばかり")),
    CorpusRow("行く", "行かんとする", "v5", listOf("-んとする")),
    CorpusRow("行く", "行かざる", "v5", listOf("-ざる")),
    CorpusRow("行く", "行かねば", "v5", listOf("-ねば")),
    CorpusRow("行く", "行かにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("行く", "行き", "v5", listOf("continuative")),
    CorpusRow("行く", "行きましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("行く", "行きませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("行く", "行きましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category3Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("行く", "行こう", "v5", listOf("volitional")),
    CorpusRow("行く", "行かう", "v5", listOf("volitional")),
    CorpusRow("行く", "行こっか", "v5", listOf("volitional slang")),
    CorpusRow("行く", "行くまい", "v5", listOf("-まい")),
    CorpusRow("行く", "行かされる", "v5", listOf("short causative", "passive")),
    CorpusRow("行く", "行っておく", "v5", listOf("-て", "-おく")),
    CorpusRow("行く", "行いとく", "v5", listOf("-て", "-おく")),
    CorpusRow("行く", "行かないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("行く", "行かないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("行く", "行っている", "v5", listOf("-て", "-いる")),
    CorpusRow("行く", "行ってゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("行く", "行っておる", "v5", listOf("-て", "-いる")),
    CorpusRow("行く", "行ってる", "v5", listOf("-て", "-いる")),
    CorpusRow("行く", "行っとる", "v5", listOf("-て", "-いる")),
    CorpusRow("行く", "行ってしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("行く", "行きやがる", "v5", listOf("-やがる")),
    CorpusRow("行く", "行きやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("行く", "行きやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("行く", "行きやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("行く", "行きますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("行く", "行きましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("行く", "行きますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("行く", "行きませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category3(): CorpusCategory = CorpusCategory(
    category = "-く verbs",
    valid = true,
    rows = category3Chunk0() + category3Chunk1(),
)

private fun category4Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("泳ぐ", "泳ぐ", "v5", listOf()),
    CorpusRow("泳ぐ", "泳ぎます", "v5", listOf("-ます")),
    CorpusRow("泳ぐ", "泳いだ", "v5", listOf("-た")),
    CorpusRow("泳ぐ", "泳ぎました", "v5", listOf("-ます", "-た")),
    CorpusRow("泳ぐ", "泳いで", "v5", listOf("-て")),
    CorpusRow("泳ぐ", "泳げる", "v5", listOf("potential")),
    CorpusRow("泳ぐ", "泳がれる", "v5", listOf("passive")),
    CorpusRow("泳ぐ", "泳がせる", "v5", listOf("causative")),
    CorpusRow("泳ぐ", "泳がす", "v5", listOf("short causative")),
    CorpusRow("泳ぐ", "泳がします", "v5", listOf("short causative", "-ます")),
    CorpusRow("泳ぐ", "泳がせられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("泳ぐ", "泳げ", "v5", listOf("imperative")),
    CorpusRow("泳ぐ", "泳がない", "v5", listOf("negative")),
    CorpusRow("泳ぐ", "泳ぎません", "v5", listOf("-ます", "negative")),
    CorpusRow("泳ぐ", "泳がなかった", "v5", listOf("negative", "-た")),
    CorpusRow("泳ぐ", "泳ぎませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("泳ぐ", "泳がなくて", "v5", listOf("negative", "-て")),
    CorpusRow("泳ぐ", "泳げない", "v5", listOf("potential", "negative")),
    CorpusRow("泳ぐ", "泳がれない", "v5", listOf("passive", "negative")),
    CorpusRow("泳ぐ", "泳がせない", "v5", listOf("causative", "negative")),
    CorpusRow("泳ぐ", "泳がさない", "v5", listOf("short causative", "negative")),
    CorpusRow("泳ぐ", "泳がせられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("泳ぐ", "泳ぎまして", "v5", listOf("-ます", "-て")),
    CorpusRow("泳ぐ", "泳げば", "v5", listOf("-ば")),
    CorpusRow("泳ぐ", "泳ぎゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("泳ぐ", "泳いじゃ", "v5", listOf("-ちゃ")),
    CorpusRow("泳ぐ", "泳いじゃう", "v5", listOf("-ちゃう")),
    CorpusRow("泳ぐ", "泳いじまう", "v5", listOf("-ちまう")),
    CorpusRow("泳ぐ", "泳ぎなさい", "v5", listOf("-なさい")),
    CorpusRow("泳ぐ", "泳ぎそう", "v5", listOf("-そう")),
    CorpusRow("泳ぐ", "泳ぎさう", "v5", listOf("-そう")),
    CorpusRow("泳ぐ", "泳ぎすぎる", "v5", listOf("-すぎる")),
    CorpusRow("泳ぐ", "泳ぎ過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("泳ぐ", "泳ぎたい", "v5", listOf("-たい")),
    CorpusRow("泳ぐ", "泳ぎたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("泳ぐ", "泳いだら", "v5", listOf("-たら")),
    CorpusRow("泳ぐ", "泳いだり", "v5", listOf("-たり")),
    CorpusRow("泳ぐ", "泳がず", "v5", listOf("-ず")),
    CorpusRow("泳ぐ", "泳がぬ", "v5", listOf("-ぬ")),
    CorpusRow("泳ぐ", "泳がん", "v5", listOf("-ん")),
    CorpusRow("泳ぐ", "泳がんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("泳ぐ", "泳がんばかり", "v5", listOf("-んばかり")),
    CorpusRow("泳ぐ", "泳がんとする", "v5", listOf("-んとする")),
    CorpusRow("泳ぐ", "泳がざる", "v5", listOf("-ざる")),
    CorpusRow("泳ぐ", "泳がねば", "v5", listOf("-ねば")),
    CorpusRow("泳ぐ", "泳がにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("泳ぐ", "泳ぎ", "v5", listOf("continuative")),
    CorpusRow("泳ぐ", "泳ぎましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("泳ぐ", "泳ぎませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("泳ぐ", "泳ぎましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category4Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("泳ぐ", "泳ごう", "v5", listOf("volitional")),
    CorpusRow("泳ぐ", "泳がう", "v5", listOf("volitional")),
    CorpusRow("泳ぐ", "泳ごっか", "v5", listOf("volitional slang")),
    CorpusRow("泳ぐ", "泳ぐまい", "v5", listOf("-まい")),
    CorpusRow("泳ぐ", "泳がされる", "v5", listOf("short causative", "passive")),
    CorpusRow("泳ぐ", "泳いでおく", "v5", listOf("-て", "-おく")),
    CorpusRow("泳ぐ", "泳いどく", "v5", listOf("-て", "-おく")),
    CorpusRow("泳ぐ", "泳がないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("泳ぐ", "泳がないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("泳ぐ", "泳いでいる", "v5", listOf("-て", "-いる")),
    CorpusRow("泳ぐ", "泳いでゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("泳ぐ", "泳いでおる", "v5", listOf("-て", "-いる")),
    CorpusRow("泳ぐ", "泳いでる", "v5", listOf("-て", "-いる")),
    CorpusRow("泳ぐ", "泳いでしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("泳ぐ", "泳ぎやがる", "v5", listOf("-やがる")),
    CorpusRow("泳ぐ", "泳ぎやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("泳ぐ", "泳ぎやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("泳ぐ", "泳ぎやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("泳ぐ", "泳ぎますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("泳ぐ", "泳ぎましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("泳ぐ", "泳ぎますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("泳ぐ", "泳ぎませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category4(): CorpusCategory = CorpusCategory(
    category = "-ぐ verbs",
    valid = true,
    rows = category4Chunk0() + category4Chunk1(),
)

private fun category5Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("話す", "話す", "v5", listOf()),
    CorpusRow("話す", "話します", "v5", listOf("-ます")),
    CorpusRow("話す", "話した", "v5", listOf("-た")),
    CorpusRow("話す", "話しました", "v5", listOf("-ます", "-た")),
    CorpusRow("話す", "話して", "v5", listOf("-て")),
    CorpusRow("話す", "話せる", "v5", listOf("potential")),
    CorpusRow("話す", "話される", "v5", listOf("passive")),
    CorpusRow("話す", "話させる", "v5", listOf("causative")),
    CorpusRow("話す", "話さす", "v5", listOf("short causative")),
    CorpusRow("話す", "話さします", "v5", listOf("short causative", "-ます")),
    CorpusRow("話す", "話させられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("話す", "話せ", "v5", listOf("imperative")),
    CorpusRow("話す", "話さない", "v5", listOf("negative")),
    CorpusRow("話す", "話しません", "v5", listOf("-ます", "negative")),
    CorpusRow("話す", "話さなかった", "v5", listOf("negative", "-た")),
    CorpusRow("話す", "話しませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("話す", "話さなくて", "v5", listOf("negative", "-て")),
    CorpusRow("話す", "話せない", "v5", listOf("potential", "negative")),
    CorpusRow("話す", "話されない", "v5", listOf("passive", "negative")),
    CorpusRow("話す", "話させない", "v5", listOf("causative", "negative")),
    CorpusRow("話す", "話ささない", "v5", listOf("short causative", "negative")),
    CorpusRow("話す", "話させられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("話す", "話しまして", "v5", listOf("-ます", "-て")),
    CorpusRow("話す", "話せば", "v5", listOf("-ば")),
    CorpusRow("話す", "話しゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("話す", "話しちゃ", "v5", listOf("-ちゃ")),
    CorpusRow("話す", "話しちゃう", "v5", listOf("-ちゃう")),
    CorpusRow("話す", "話しちまう", "v5", listOf("-ちまう")),
    CorpusRow("話す", "話しなさい", "v5", listOf("-なさい")),
    CorpusRow("話す", "話しそう", "v5", listOf("-そう")),
    CorpusRow("話す", "話しさう", "v5", listOf("-そう")),
    CorpusRow("話す", "話しすぎる", "v5", listOf("-すぎる")),
    CorpusRow("話す", "話し過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("話す", "話したい", "v5", listOf("-たい")),
    CorpusRow("話す", "話したがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("話す", "話したら", "v5", listOf("-たら")),
    CorpusRow("話す", "話したり", "v5", listOf("-たり")),
    CorpusRow("話す", "話さず", "v5", listOf("-ず")),
    CorpusRow("話す", "話さぬ", "v5", listOf("-ぬ")),
    CorpusRow("話す", "話さん", "v5", listOf("-ん")),
    CorpusRow("話す", "話さんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("話す", "話さんばかり", "v5", listOf("-んばかり")),
    CorpusRow("話す", "話さんとする", "v5", listOf("-んとする")),
    CorpusRow("話す", "話さざる", "v5", listOf("-ざる")),
    CorpusRow("話す", "話さねば", "v5", listOf("-ねば")),
    CorpusRow("話す", "話さにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("話す", "話し", "v5", listOf("continuative")),
    CorpusRow("話す", "話しましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("話す", "話しませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("話す", "話しましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category5Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("話す", "話そう", "v5", listOf("volitional")),
    CorpusRow("話す", "話さう", "v5", listOf("volitional")),
    CorpusRow("話す", "話そっか", "v5", listOf("volitional slang")),
    CorpusRow("話す", "話すまい", "v5", listOf("-まい")),
    CorpusRow("話す", "話しておく", "v5", listOf("-て", "-おく")),
    CorpusRow("話す", "話しとく", "v5", listOf("-て", "-おく")),
    CorpusRow("話す", "話さないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("話す", "話さないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("話す", "話している", "v5", listOf("-て", "-いる")),
    CorpusRow("話す", "話してゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("話す", "話しておる", "v5", listOf("-て", "-いる")),
    CorpusRow("話す", "話してる", "v5", listOf("-て", "-いる")),
    CorpusRow("話す", "話しとる", "v5", listOf("-て", "-いる")),
    CorpusRow("話す", "話してしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("話す", "話しやがる", "v5", listOf("-やがる")),
    CorpusRow("話す", "話しやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("話す", "話しやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("話す", "話しやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("増す", "増せん", "v5", listOf("potential", "-ん")),
    CorpusRow("増す", "増せんかった", "v5", listOf("potential", "-ん", "-た")),
    CorpusRow("増す", "増せんばかり", "v5", listOf("potential", "-んばかり")),
    CorpusRow("増す", "増せんとする", "v5", listOf("potential", "-んとする")),
    CorpusRow("話す", "話しますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("話す", "話しましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("話す", "話しますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("話す", "話しませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category5(): CorpusCategory = CorpusCategory(
    category = "-す verbs",
    valid = true,
    rows = category5Chunk0() + category5Chunk1(),
)

private fun category6Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("待つ", "待つ", "v5", listOf()),
    CorpusRow("待つ", "待ちます", "v5", listOf("-ます")),
    CorpusRow("待つ", "待った", "v5", listOf("-た")),
    CorpusRow("待つ", "待ちました", "v5", listOf("-ます", "-た")),
    CorpusRow("待つ", "待って", "v5", listOf("-て")),
    CorpusRow("待つ", "待てる", "v5", listOf("potential")),
    CorpusRow("待つ", "待たれる", "v5", listOf("passive")),
    CorpusRow("待つ", "待たせる", "v5", listOf("causative")),
    CorpusRow("待つ", "待たす", "v5", listOf("short causative")),
    CorpusRow("待つ", "待たします", "v5", listOf("short causative", "-ます")),
    CorpusRow("待つ", "待たせられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("待つ", "待て", "v5", listOf("imperative")),
    CorpusRow("待つ", "待たない", "v5", listOf("negative")),
    CorpusRow("待つ", "待ちません", "v5", listOf("-ます", "negative")),
    CorpusRow("待つ", "待たなかった", "v5", listOf("negative", "-た")),
    CorpusRow("待つ", "待ちませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("待つ", "待たなくて", "v5", listOf("negative", "-て")),
    CorpusRow("待つ", "待てない", "v5", listOf("potential", "negative")),
    CorpusRow("待つ", "待たれない", "v5", listOf("passive", "negative")),
    CorpusRow("待つ", "待たせない", "v5", listOf("causative", "negative")),
    CorpusRow("待つ", "待たさない", "v5", listOf("short causative", "negative")),
    CorpusRow("待つ", "待たせられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("待つ", "待ちまして", "v5", listOf("-ます", "-て")),
    CorpusRow("待つ", "待てば", "v5", listOf("-ば")),
    CorpusRow("待つ", "待ちゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("待つ", "待っちゃ", "v5", listOf("-ちゃ")),
    CorpusRow("待つ", "待っちゃう", "v5", listOf("-ちゃう")),
    CorpusRow("待つ", "待っちまう", "v5", listOf("-ちまう")),
    CorpusRow("待つ", "待ちなさい", "v5", listOf("-なさい")),
    CorpusRow("待つ", "待ちそう", "v5", listOf("-そう")),
    CorpusRow("待つ", "待ちさう", "v5", listOf("-そう")),
    CorpusRow("待つ", "待ちすぎる", "v5", listOf("-すぎる")),
    CorpusRow("待つ", "待ち過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("待つ", "待ちたい", "v5", listOf("-たい")),
    CorpusRow("待つ", "待ちたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("待つ", "待ったら", "v5", listOf("-たら")),
    CorpusRow("待つ", "待ったり", "v5", listOf("-たり")),
    CorpusRow("待つ", "待たず", "v5", listOf("-ず")),
    CorpusRow("待つ", "待たぬ", "v5", listOf("-ぬ")),
    CorpusRow("待つ", "待たん", "v5", listOf("-ん")),
    CorpusRow("待つ", "待たんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("待つ", "待たんばかり", "v5", listOf("-んばかり")),
    CorpusRow("待つ", "待たんとする", "v5", listOf("-んとする")),
    CorpusRow("待つ", "待たざる", "v5", listOf("-ざる")),
    CorpusRow("待つ", "待たねば", "v5", listOf("-ねば")),
    CorpusRow("待つ", "待たにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("待つ", "待ち", "v5", listOf("continuative")),
    CorpusRow("待つ", "待ちましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("待つ", "待ちませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("待つ", "待ちましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category6Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("待つ", "待とう", "v5", listOf("volitional")),
    CorpusRow("待つ", "待たう", "v5", listOf("volitional")),
    CorpusRow("待つ", "待とっか", "v5", listOf("volitional slang")),
    CorpusRow("待つ", "待つまい", "v5", listOf("-まい")),
    CorpusRow("待つ", "待たされる", "v5", listOf("short causative", "passive")),
    CorpusRow("待つ", "待っておく", "v5", listOf("-て", "-おく")),
    CorpusRow("待つ", "待っとく", "v5", listOf("-て", "-おく")),
    CorpusRow("待つ", "待たないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("待つ", "待たないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("待つ", "待っている", "v5", listOf("-て", "-いる")),
    CorpusRow("待つ", "待ってゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("待つ", "待っておる", "v5", listOf("-て", "-いる")),
    CorpusRow("待つ", "待ってる", "v5", listOf("-て", "-いる")),
    CorpusRow("待つ", "待っとる", "v5", listOf("-て", "-いる")),
    CorpusRow("待つ", "待ってしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("待つ", "待ちやがる", "v5", listOf("-やがる")),
    CorpusRow("待つ", "待ちやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("待つ", "待ちやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("待つ", "待ちやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("待つ", "待ちますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("待つ", "待ちましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("待つ", "待ちますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("待つ", "待ちませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category6(): CorpusCategory = CorpusCategory(
    category = "-つ verbs",
    valid = true,
    rows = category6Chunk0() + category6Chunk1(),
)

private fun category7Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("死ぬ", "死ぬ", "v5", listOf()),
    CorpusRow("死ぬ", "死にます", "v5", listOf("-ます")),
    CorpusRow("死ぬ", "死んだ", "v5", listOf("-た")),
    CorpusRow("死ぬ", "死にました", "v5", listOf("-ます", "-た")),
    CorpusRow("死ぬ", "死んで", "v5", listOf("-て")),
    CorpusRow("死ぬ", "死ねる", "v5", listOf("potential")),
    CorpusRow("死ぬ", "死なれる", "v5", listOf("passive")),
    CorpusRow("死ぬ", "死なせる", "v5", listOf("causative")),
    CorpusRow("死ぬ", "死なす", "v5", listOf("short causative")),
    CorpusRow("死ぬ", "死なします", "v5", listOf("short causative", "-ます")),
    CorpusRow("死ぬ", "死なせられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("死ぬ", "死ね", "v5", listOf("imperative")),
    CorpusRow("死ぬ", "死なない", "v5", listOf("negative")),
    CorpusRow("死ぬ", "死にません", "v5", listOf("-ます", "negative")),
    CorpusRow("死ぬ", "死ななかった", "v5", listOf("negative", "-た")),
    CorpusRow("死ぬ", "死にませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("死ぬ", "死ななくて", "v5", listOf("negative", "-て")),
    CorpusRow("死ぬ", "死ねない", "v5", listOf("potential", "negative")),
    CorpusRow("死ぬ", "死なれない", "v5", listOf("passive", "negative")),
    CorpusRow("死ぬ", "死なせない", "v5", listOf("causative", "negative")),
    CorpusRow("死ぬ", "死なさない", "v5", listOf("short causative", "negative")),
    CorpusRow("死ぬ", "死なせられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("死ぬ", "死にまして", "v5", listOf("-ます", "-て")),
    CorpusRow("死ぬ", "死ねば", "v5", listOf("-ば")),
    CorpusRow("死ぬ", "死にゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("死ぬ", "死んじゃ", "v5", listOf("-ちゃ")),
    CorpusRow("死ぬ", "死んじゃう", "v5", listOf("-ちゃう")),
    CorpusRow("死ぬ", "死んじまう", "v5", listOf("-ちまう")),
    CorpusRow("死ぬ", "死になさい", "v5", listOf("-なさい")),
    CorpusRow("死ぬ", "死にそう", "v5", listOf("-そう")),
    CorpusRow("死ぬ", "死にさう", "v5", listOf("-そう")),
    CorpusRow("死ぬ", "死にすぎる", "v5", listOf("-すぎる")),
    CorpusRow("死ぬ", "死に過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("死ぬ", "死にたい", "v5", listOf("-たい")),
    CorpusRow("死ぬ", "死にたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("死ぬ", "死んだら", "v5", listOf("-たら")),
    CorpusRow("死ぬ", "死んだり", "v5", listOf("-たり")),
    CorpusRow("死ぬ", "死なず", "v5", listOf("-ず")),
    CorpusRow("死ぬ", "死なぬ", "v5", listOf("-ぬ")),
    CorpusRow("死ぬ", "死なん", "v5", listOf("-ん")),
    CorpusRow("死ぬ", "死なんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("死ぬ", "死なんばかり", "v5", listOf("-んばかり")),
    CorpusRow("死ぬ", "死なんとする", "v5", listOf("-んとする")),
    CorpusRow("死ぬ", "死なざる", "v5", listOf("-ざる")),
    CorpusRow("死ぬ", "死なねば", "v5", listOf("-ねば")),
    CorpusRow("死ぬ", "死なにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("死ぬ", "死に", "v5", listOf("continuative")),
    CorpusRow("死ぬ", "死にましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("死ぬ", "死にませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("死ぬ", "死にましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category7Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("死ぬ", "死のう", "v5", listOf("volitional")),
    CorpusRow("死ぬ", "死なう", "v5", listOf("volitional")),
    CorpusRow("死ぬ", "死のっか", "v5", listOf("volitional slang")),
    CorpusRow("死ぬ", "死ぬまい", "v5", listOf("-まい")),
    CorpusRow("死ぬ", "死なされる", "v5", listOf("short causative", "passive")),
    CorpusRow("死ぬ", "死んでおく", "v5", listOf("-て", "-おく")),
    CorpusRow("死ぬ", "死んどく", "v5", listOf("-て", "-おく")),
    CorpusRow("死ぬ", "死なないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("死ぬ", "死なないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("死ぬ", "死んでいる", "v5", listOf("-て", "-いる")),
    CorpusRow("死ぬ", "死んでゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("死ぬ", "死んでおる", "v5", listOf("-て", "-いる")),
    CorpusRow("死ぬ", "死んでる", "v5", listOf("-て", "-いる")),
    CorpusRow("死ぬ", "死んでしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("死ぬ", "死にやがる", "v5", listOf("-やがる")),
    CorpusRow("死ぬ", "死にやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("死ぬ", "死にやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("死ぬ", "死にやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("死ぬ", "死にますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("死ぬ", "死にましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("死ぬ", "死にますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("死ぬ", "死にませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category7(): CorpusCategory = CorpusCategory(
    category = "-ぬ verbs",
    valid = true,
    rows = category7Chunk0() + category7Chunk1(),
)

private fun category8Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("遊ぶ", "遊ぶ", "v5", listOf()),
    CorpusRow("遊ぶ", "遊びます", "v5", listOf("-ます")),
    CorpusRow("遊ぶ", "遊んだ", "v5", listOf("-た")),
    CorpusRow("遊ぶ", "遊びました", "v5", listOf("-ます", "-た")),
    CorpusRow("遊ぶ", "遊んで", "v5", listOf("-て")),
    CorpusRow("遊ぶ", "遊べる", "v5", listOf("potential")),
    CorpusRow("遊ぶ", "遊ばれる", "v5", listOf("passive")),
    CorpusRow("遊ぶ", "遊ばせる", "v5", listOf("causative")),
    CorpusRow("遊ぶ", "遊ばす", "v5", listOf("short causative")),
    CorpusRow("遊ぶ", "遊ばします", "v5", listOf("short causative", "-ます")),
    CorpusRow("遊ぶ", "遊ばせられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("遊ぶ", "遊べ", "v5", listOf("imperative")),
    CorpusRow("遊ぶ", "遊ばない", "v5", listOf("negative")),
    CorpusRow("遊ぶ", "遊びません", "v5", listOf("-ます", "negative")),
    CorpusRow("遊ぶ", "遊ばなかった", "v5", listOf("negative", "-た")),
    CorpusRow("遊ぶ", "遊びませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("遊ぶ", "遊ばなくて", "v5", listOf("negative", "-て")),
    CorpusRow("遊ぶ", "遊べない", "v5", listOf("potential", "negative")),
    CorpusRow("遊ぶ", "遊ばれない", "v5", listOf("passive", "negative")),
    CorpusRow("遊ぶ", "遊ばせない", "v5", listOf("causative", "negative")),
    CorpusRow("遊ぶ", "遊ばさない", "v5", listOf("short causative", "negative")),
    CorpusRow("遊ぶ", "遊ばせられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("遊ぶ", "遊びまして", "v5", listOf("-ます", "-て")),
    CorpusRow("遊ぶ", "遊べば", "v5", listOf("-ば")),
    CorpusRow("遊ぶ", "遊びゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("遊ぶ", "遊んじゃ", "v5", listOf("-ちゃ")),
    CorpusRow("遊ぶ", "遊んじゃう", "v5", listOf("-ちゃう")),
    CorpusRow("遊ぶ", "遊んじまう", "v5", listOf("-ちまう")),
    CorpusRow("遊ぶ", "遊びなさい", "v5", listOf("-なさい")),
    CorpusRow("遊ぶ", "遊びそう", "v5", listOf("-そう")),
    CorpusRow("遊ぶ", "遊びさう", "v5", listOf("-そう")),
    CorpusRow("遊ぶ", "遊びすぎる", "v5", listOf("-すぎる")),
    CorpusRow("遊ぶ", "遊び過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("遊ぶ", "遊びたい", "v5", listOf("-たい")),
    CorpusRow("遊ぶ", "遊びたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("遊ぶ", "遊んだら", "v5", listOf("-たら")),
    CorpusRow("遊ぶ", "遊んだり", "v5", listOf("-たり")),
    CorpusRow("遊ぶ", "遊ばず", "v5", listOf("-ず")),
    CorpusRow("遊ぶ", "遊ばぬ", "v5", listOf("-ぬ")),
    CorpusRow("遊ぶ", "遊ばん", "v5", listOf("-ん")),
    CorpusRow("遊ぶ", "遊ばんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("遊ぶ", "遊ばんばかり", "v5", listOf("-んばかり")),
    CorpusRow("遊ぶ", "遊ばんとする", "v5", listOf("-んとする")),
    CorpusRow("遊ぶ", "遊ばざる", "v5", listOf("-ざる")),
    CorpusRow("遊ぶ", "遊ばねば", "v5", listOf("-ねば")),
    CorpusRow("遊ぶ", "遊ばにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("遊ぶ", "遊び", "v5", listOf("continuative")),
    CorpusRow("遊ぶ", "遊びましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("遊ぶ", "遊びませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("遊ぶ", "遊びましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category8Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("遊ぶ", "遊ぼう", "v5", listOf("volitional")),
    CorpusRow("遊ぶ", "遊ばう", "v5", listOf("volitional")),
    CorpusRow("遊ぶ", "遊ぼっか", "v5", listOf("volitional slang")),
    CorpusRow("遊ぶ", "遊ぶまい", "v5", listOf("-まい")),
    CorpusRow("遊ぶ", "遊ばされる", "v5", listOf("short causative", "passive")),
    CorpusRow("遊ぶ", "遊んでおく", "v5", listOf("-て", "-おく")),
    CorpusRow("遊ぶ", "遊んどく", "v5", listOf("-て", "-おく")),
    CorpusRow("遊ぶ", "遊んでおく", "v5", listOf("-て", "-おく")),
    CorpusRow("遊ぶ", "遊ばないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("遊ぶ", "遊んでいる", "v5", listOf("-て", "-いる")),
    CorpusRow("遊ぶ", "遊んでゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("遊ぶ", "遊んでおる", "v5", listOf("-て", "-いる")),
    CorpusRow("遊ぶ", "遊んでる", "v5", listOf("-て", "-いる")),
    CorpusRow("遊ぶ", "遊んでしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("遊ぶ", "遊びやがる", "v5", listOf("-やがる")),
    CorpusRow("遊ぶ", "遊びやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("遊ぶ", "遊びやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("遊ぶ", "遊びやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("遊ぶ", "遊びますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("遊ぶ", "遊びましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("遊ぶ", "遊びますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("遊ぶ", "遊びませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category8(): CorpusCategory = CorpusCategory(
    category = "-ぶ verbs",
    valid = true,
    rows = category8Chunk0() + category8Chunk1(),
)

private fun category9Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("飲む", "飲む", "v5", listOf()),
    CorpusRow("飲む", "飲みます", "v5", listOf("-ます")),
    CorpusRow("飲む", "飲んだ", "v5", listOf("-た")),
    CorpusRow("飲む", "飲みました", "v5", listOf("-ます", "-た")),
    CorpusRow("飲む", "飲んで", "v5", listOf("-て")),
    CorpusRow("飲む", "飲める", "v5", listOf("potential")),
    CorpusRow("飲む", "飲まれる", "v5", listOf("passive")),
    CorpusRow("飲む", "飲ませる", "v5", listOf("causative")),
    CorpusRow("飲む", "飲ます", "v5", listOf("short causative")),
    CorpusRow("飲む", "飲まします", "v5", listOf("short causative", "-ます")),
    CorpusRow("飲む", "飲ませられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("飲む", "飲め", "v5", listOf("imperative")),
    CorpusRow("飲む", "飲まない", "v5", listOf("negative")),
    CorpusRow("飲む", "飲みません", "v5", listOf("-ます", "negative")),
    CorpusRow("飲む", "飲まなかった", "v5", listOf("negative", "-た")),
    CorpusRow("飲む", "飲みませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("飲む", "飲まなくて", "v5", listOf("negative", "-て")),
    CorpusRow("飲む", "飲めない", "v5", listOf("potential", "negative")),
    CorpusRow("飲む", "飲まれない", "v5", listOf("passive", "negative")),
    CorpusRow("飲む", "飲ませない", "v5", listOf("causative", "negative")),
    CorpusRow("飲む", "飲まさない", "v5", listOf("short causative", "negative")),
    CorpusRow("飲む", "飲ませられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("飲む", "飲みまして", "v5", listOf("-ます", "-て")),
    CorpusRow("飲む", "飲めば", "v5", listOf("-ば")),
    CorpusRow("飲む", "飲みゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("飲む", "飲んじゃ", "v5", listOf("-ちゃ")),
    CorpusRow("飲む", "飲んじゃう", "v5", listOf("-ちゃう")),
    CorpusRow("飲む", "飲んじまう", "v5", listOf("-ちまう")),
    CorpusRow("飲む", "飲みなさい", "v5", listOf("-なさい")),
    CorpusRow("飲む", "飲みそう", "v5", listOf("-そう")),
    CorpusRow("飲む", "飲みさう", "v5", listOf("-そう")),
    CorpusRow("飲む", "飲みすぎる", "v5", listOf("-すぎる")),
    CorpusRow("飲む", "飲み過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("飲む", "飲みたい", "v5", listOf("-たい")),
    CorpusRow("飲む", "飲みたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("飲む", "飲んだら", "v5", listOf("-たら")),
    CorpusRow("飲む", "飲んだり", "v5", listOf("-たり")),
    CorpusRow("飲む", "飲まず", "v5", listOf("-ず")),
    CorpusRow("飲む", "飲まぬ", "v5", listOf("-ぬ")),
    CorpusRow("飲む", "飲まん", "v5", listOf("-ん")),
    CorpusRow("飲む", "飲まんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("飲む", "飲まんばかり", "v5", listOf("-んばかり")),
    CorpusRow("飲む", "飲まんとする", "v5", listOf("-んとする")),
    CorpusRow("飲む", "飲まざる", "v5", listOf("-ざる")),
    CorpusRow("飲む", "飲まねば", "v5", listOf("-ねば")),
    CorpusRow("飲む", "飲まにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("飲む", "飲み", "v5", listOf("continuative")),
    CorpusRow("飲む", "飲みましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("飲む", "飲みませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("飲む", "飲みましょっか", "v5", listOf("-ます", "volitional slang")),
)

private fun category9Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("飲む", "飲もう", "v5", listOf("volitional")),
    CorpusRow("飲む", "飲まう", "v5", listOf("volitional")),
    CorpusRow("飲む", "飲もっか", "v5", listOf("volitional slang")),
    CorpusRow("飲む", "飲むまい", "v5", listOf("-まい")),
    CorpusRow("飲む", "飲まされる", "v5", listOf("short causative", "passive")),
    CorpusRow("飲む", "飲んでおく", "v5", listOf("-て", "-おく")),
    CorpusRow("飲む", "飲んどく", "v5", listOf("-て", "-おく")),
    CorpusRow("飲む", "飲まないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("飲む", "飲まないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("飲む", "飲んでいる", "v5", listOf("-て", "-いる")),
    CorpusRow("飲む", "飲んでゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("飲む", "飲んでおる", "v5", listOf("-て", "-いる")),
    CorpusRow("飲む", "飲んでる", "v5", listOf("-て", "-いる")),
    CorpusRow("飲む", "飲んでしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("飲む", "飲みやがる", "v5", listOf("-やがる")),
    CorpusRow("飲む", "飲みやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("飲む", "飲みやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("飲む", "飲みやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("飲む", "飲みますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("飲む", "飲みましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("飲む", "飲みますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("飲む", "飲みませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category9(): CorpusCategory = CorpusCategory(
    category = "-む verbs",
    valid = true,
    rows = category9Chunk0() + category9Chunk1(),
)

private fun category10Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("作る", "作る", "v5", listOf()),
    CorpusRow("作る", "作ります", "v5", listOf("-ます")),
    CorpusRow("作る", "作った", "v5", listOf("-た")),
    CorpusRow("作る", "作りました", "v5", listOf("-ます", "-た")),
    CorpusRow("作る", "作って", "v5", listOf("-て")),
    CorpusRow("作る", "作れる", "v5", listOf("potential")),
    CorpusRow("作る", "作られる", "v5", listOf("passive")),
    CorpusRow("作る", "作らせる", "v5", listOf("causative")),
    CorpusRow("作る", "作らす", "v5", listOf("short causative")),
    CorpusRow("作る", "作らします", "v5", listOf("short causative", "-ます")),
    CorpusRow("作る", "作らせられる", "v5", listOf("causative", "potential or passive")),
    CorpusRow("作る", "作れ", "v5", listOf("imperative")),
    CorpusRow("作る", "作らない", "v5", listOf("negative")),
    CorpusRow("作る", "作りません", "v5", listOf("-ます", "negative")),
    CorpusRow("作る", "作らなかった", "v5", listOf("negative", "-た")),
    CorpusRow("作る", "作りませんでした", "v5", listOf("-ます", "negative", "-た")),
    CorpusRow("作る", "作らなくて", "v5", listOf("negative", "-て")),
    CorpusRow("作る", "作れない", "v5", listOf("potential", "negative")),
    CorpusRow("作る", "作られない", "v5", listOf("passive", "negative")),
    CorpusRow("作る", "作らせない", "v5", listOf("causative", "negative")),
    CorpusRow("作る", "作らさない", "v5", listOf("short causative", "negative")),
    CorpusRow("作る", "作らせられない", "v5", listOf("causative", "potential or passive", "negative")),
    CorpusRow("作る", "作りまして", "v5", listOf("-ます", "-て")),
    CorpusRow("作る", "作れば", "v5", listOf("-ば")),
    CorpusRow("作る", "作りゃ", "v5", listOf("-ば", "-ゃ")),
    CorpusRow("作る", "作っちゃ", "v5", listOf("-ちゃ")),
    CorpusRow("作る", "作っちゃう", "v5", listOf("-ちゃう")),
    CorpusRow("作る", "作っちまう", "v5", listOf("-ちまう")),
    CorpusRow("作る", "作りなさい", "v5", listOf("-なさい")),
    CorpusRow("作る", "作りそう", "v5", listOf("-そう")),
    CorpusRow("作る", "作りさう", "v5", listOf("-そう")),
    CorpusRow("作る", "作りすぎる", "v5", listOf("-すぎる")),
    CorpusRow("作る", "作り過ぎる", "v5", listOf("-過ぎる")),
    CorpusRow("作る", "作りたい", "v5", listOf("-たい")),
    CorpusRow("作る", "作りたがる", "v5", listOf("-たい", "-がる")),
    CorpusRow("作る", "作ったら", "v5", listOf("-たら")),
    CorpusRow("作る", "作ったり", "v5", listOf("-たり")),
    CorpusRow("作る", "作らず", "v5", listOf("-ず")),
    CorpusRow("作る", "作らぬ", "v5", listOf("-ぬ")),
    CorpusRow("作る", "作らん", "v5", listOf("-ん")),
    CorpusRow("作る", "作らんかった", "v5", listOf("-ん", "-た")),
    CorpusRow("作る", "作らざる", "v5", listOf("-ざる")),
    CorpusRow("作る", "作らねば", "v5", listOf("-ねば")),
    CorpusRow("作る", "作らにゃ", "v5", listOf("-ねば", "-ゃ")),
    CorpusRow("作る", "作り", "v5", listOf("continuative")),
    CorpusRow("作る", "作りましょう", "v5", listOf("-ます", "volitional")),
    CorpusRow("作る", "作りませう", "v5", listOf("-ます", "volitional")),
    CorpusRow("作る", "作りましょっか", "v5", listOf("-ます", "volitional slang")),
    CorpusRow("作る", "作ろう", "v5", listOf("volitional")),
    CorpusRow("作る", "作らう", "v5", listOf("volitional")),
)

private fun category10Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("作る", "作ろっか", "v5", listOf("volitional slang")),
    CorpusRow("作る", "作るまい", "v5", listOf("-まい")),
    CorpusRow("作る", "作らされる", "v5", listOf("short causative", "passive")),
    CorpusRow("作る", "作っておく", "v5", listOf("-て", "-おく")),
    CorpusRow("作る", "作っとく", "v5", listOf("-て", "-おく")),
    CorpusRow("作る", "作らないでおく", "v5", listOf("negative", "-おく")),
    CorpusRow("作る", "作らないどく", "v5", listOf("negative", "-おく")),
    CorpusRow("作る", "作っている", "v5", listOf("-て", "-いる")),
    CorpusRow("作る", "作ってゐる", "v5", listOf("-て", "-いる")),
    CorpusRow("作る", "作っておる", "v5", listOf("-て", "-いる")),
    CorpusRow("作る", "作ってる", "v5", listOf("-て", "-いる")),
    CorpusRow("作る", "作っとる", "v5", listOf("-て", "-いる")),
    CorpusRow("作る", "作ってしまう", "v5", listOf("-て", "-しまう")),
    CorpusRow("作る", "作りやがる", "v5", listOf("-やがる")),
    CorpusRow("作る", "作りやがって", "v5", listOf("-やがる", "-て")),
    CorpusRow("作る", "作りやがった", "v5", listOf("-やがる", "-た")),
    CorpusRow("作る", "作りやがれ", "v5", listOf("-やがる", "imperative")),
    CorpusRow("作る", "作りますまい", "v5", listOf("-ます", "-まい")),
    CorpusRow("作る", "作りましたら", "v5", listOf("-ます", "-たら")),
    CorpusRow("作る", "作りますれば", "v5", listOf("-ます", "-ば")),
    CorpusRow("作る", "作りませんかった", "v5", listOf("-ます", "negative", "-た")),
)

private fun category10(): CorpusCategory = CorpusCategory(
    category = "godan verbs",
    valid = true,
    rows = category10Chunk0() + category10Chunk1(),
)

private fun category11Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("いらっしゃる", "いらっしゃいます", "v5", listOf("-ます")),
    CorpusRow("ござる", "ございました", "v5", listOf("-ます", "-た")),
    CorpusRow("なさる", "なさいます", "v5", listOf("-ます")),
    CorpusRow("くださる", "くださいます", "v5", listOf("-ます")),
    CorpusRow("下さる", "下さいます", "v5", listOf("-ます")),
    CorpusRow("おっしゃる", "おっしゃいました", "v5", listOf("-ます", "-た")),
    CorpusRow("仰る", "仰いました", "v5", listOf("-ます", "-た")),
    CorpusRow("仰有る", "仰有いました", "v5", listOf("-ます", "-た")),
    CorpusRow("いらっしゃる", "いらっしゃいません", "v5", listOf("-ます", "negative")),
)

private fun category11(): CorpusCategory = CorpusCategory(
    category = "special honorific -ます verbs",
    valid = true,
    rows = category11Chunk0(),
)

private fun category12Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("為る", "為る", "vs", listOf()),
    CorpusRow("為る", "為ます", "vs", listOf("-ます")),
    CorpusRow("為る", "為た", "vs", listOf("-た")),
    CorpusRow("為る", "為ました", "vs", listOf("-ます", "-た")),
    CorpusRow("為る", "為て", "vs", listOf("-て")),
    CorpusRow("為る", "為られる", "vs", listOf("potential or passive")),
    CorpusRow("為る", "為れる", "vs", listOf("passive")),
    CorpusRow("為る", "為せる", "vs", listOf("causative")),
    CorpusRow("為る", "為させる", "vs", listOf("causative")),
    CorpusRow("為る", "為す", "vs", listOf("short causative")),
    CorpusRow("為る", "為します", "vs", listOf("short causative", "-ます")),
    CorpusRow("為る", "為せられる", "vs", listOf("causative", "potential or passive")),
    CorpusRow("為る", "為させられる", "vs", listOf("causative", "potential or passive")),
    CorpusRow("為る", "為ろ", "vs", listOf("imperative")),
    CorpusRow("為る", "為ない", "vs", listOf("negative")),
    CorpusRow("為る", "為ません", "vs", listOf("-ます", "negative")),
    CorpusRow("為る", "為なかった", "vs", listOf("negative", "-た")),
    CorpusRow("為る", "為ませんでした", "vs", listOf("-ます", "negative", "-た")),
    CorpusRow("為る", "為なくて", "vs", listOf("negative", "-て")),
    CorpusRow("為る", "為られない", "vs", listOf("potential or passive", "negative")),
    CorpusRow("為る", "為れない", "vs", listOf("passive", "negative")),
    CorpusRow("為る", "為せない", "vs", listOf("causative", "negative")),
    CorpusRow("為る", "為させない", "vs", listOf("causative", "negative")),
    CorpusRow("為る", "為さない", "vs", listOf("short causative", "negative")),
    CorpusRow("為る", "為せられない", "vs", listOf("causative", "potential or passive", "negative")),
    CorpusRow("為る", "為させられない", "vs", listOf("causative", "potential or passive", "negative")),
    CorpusRow("為る", "為まして", "vs", listOf("-ます", "-て")),
    CorpusRow("為る", "為れば", "vs", listOf("-ば")),
    CorpusRow("為る", "為りゃ", "vs", listOf("-ば", "-ゃ")),
    CorpusRow("為る", "為ちゃ", "vs", listOf("-ちゃ")),
    CorpusRow("為る", "為ちゃう", "vs", listOf("-ちゃう")),
    CorpusRow("為る", "為ちまう", "vs", listOf("-ちまう")),
    CorpusRow("為る", "為なさい", "vs", listOf("-なさい")),
    CorpusRow("為る", "為そう", "vs", listOf("-そう")),
    CorpusRow("為る", "為さう", "vs", listOf("-そう")),
    CorpusRow("為る", "為すぎる", "vs", listOf("-すぎる")),
    CorpusRow("為る", "為過ぎる", "vs", listOf("-過ぎる")),
    CorpusRow("為る", "為たい", "vs", listOf("-たい")),
    CorpusRow("為る", "為たがる", "vs", listOf("-たい", "-がる")),
    CorpusRow("為る", "為たら", "vs", listOf("-たら")),
    CorpusRow("為る", "為たり", "vs", listOf("-たり")),
    CorpusRow("為る", "為ず", "vs", listOf("-ず")),
    CorpusRow("為る", "為ぬ", "vs", listOf("-ぬ")),
    CorpusRow("為る", "為ん", "vs", listOf("-ん")),
    CorpusRow("為る", "為んかった", "vs", listOf("-ん", "-た")),
    CorpusRow("為る", "為んばかり", "vs", listOf("-んばかり")),
    CorpusRow("為る", "為んとする", "vs", listOf("-んとする")),
    CorpusRow("為る", "為ざる", "vs", listOf("-ざる")),
    CorpusRow("為る", "為ねば", "vs", listOf("-ねば")),
    CorpusRow("為る", "為にゃ", "vs", listOf("-ねば", "-ゃ")),
)

private fun category12Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("為る", "為ましょう", "vs", listOf("-ます", "volitional")),
    CorpusRow("為る", "為ませう", "vs", listOf("-ます", "volitional")),
    CorpusRow("為る", "為ましょっか", "vs", listOf("-ます", "volitional slang")),
    CorpusRow("為る", "為よう", "vs", listOf("volitional")),
    CorpusRow("為る", "為やう", "vs", listOf("volitional")),
    CorpusRow("為る", "為よっか", "vs", listOf("volitional slang")),
    CorpusRow("為る", "為るまい", "vs", listOf("-まい")),
    CorpusRow("為る", "為まい", "vs", listOf("-まい")),
    CorpusRow("為る", "為ておく", "vs", listOf("-て", "-おく")),
    CorpusRow("為る", "為とく", "vs", listOf("-て", "-おく")),
    CorpusRow("為る", "為ないでおく", "vs", listOf("negative", "-おく")),
    CorpusRow("為る", "為ないどく", "vs", listOf("negative", "-おく")),
    CorpusRow("為る", "為ている", "vs", listOf("-て", "-いる")),
    CorpusRow("為る", "為てゐる", "vs", listOf("-て", "-いる")),
    CorpusRow("為る", "為ておる", "vs", listOf("-て", "-いる")),
    CorpusRow("為る", "為てる", "vs", listOf("-て", "-いる")),
    CorpusRow("為る", "為とる", "vs", listOf("-て", "-いる")),
    CorpusRow("為る", "為てしまう", "vs", listOf("-て", "-しまう")),
    CorpusRow("為る", "為ますまい", "vs", listOf("-ます", "-まい")),
    CorpusRow("為る", "為ましたら", "vs", listOf("-ます", "-たら")),
    CorpusRow("為る", "為ますれば", "vs", listOf("-ます", "-ば")),
    CorpusRow("為る", "為ませんかった", "vs", listOf("-ます", "negative", "-た")),
    CorpusRow("する", "する", "vs", listOf()),
    CorpusRow("する", "します", "vs", listOf("-ます")),
    CorpusRow("する", "した", "vs", listOf("-た")),
    CorpusRow("する", "しました", "vs", listOf("-ます", "-た")),
    CorpusRow("する", "して", "vs", listOf("-て")),
    CorpusRow("する", "できる", "vs", listOf("potential")),
    CorpusRow("する", "出来る", "vs", listOf("potential")),
    CorpusRow("する", "せられる", "vs", listOf("potential or passive")),
    CorpusRow("する", "される", "vs", listOf("passive")),
    CorpusRow("する", "させる", "vs", listOf("causative")),
    CorpusRow("する", "せさせる", "vs", listOf("causative")),
    CorpusRow("する", "さす", "vs", listOf("short causative")),
    CorpusRow("する", "さします", "vs", listOf("short causative", "-ます")),
    CorpusRow("する", "させられる", "vs", listOf("causative", "potential or passive")),
    CorpusRow("する", "せさせられる", "vs", listOf("causative", "potential or passive")),
    CorpusRow("する", "しろ", "vs", listOf("imperative")),
    CorpusRow("する", "しない", "vs", listOf("negative")),
    CorpusRow("する", "しません", "vs", listOf("-ます", "negative")),
    CorpusRow("する", "しなかった", "vs", listOf("negative", "-た")),
    CorpusRow("する", "しませんでした", "vs", listOf("-ます", "negative", "-た")),
    CorpusRow("する", "しなくて", "vs", listOf("negative", "-て")),
    CorpusRow("する", "せられない", "vs", listOf("potential or passive", "negative")),
    CorpusRow("する", "されない", "vs", listOf("passive", "negative")),
    CorpusRow("する", "させない", "vs", listOf("causative", "negative")),
    CorpusRow("する", "せさせない", "vs", listOf("causative", "negative")),
    CorpusRow("する", "ささない", "vs", listOf("short causative", "negative")),
    CorpusRow("する", "させられない", "vs", listOf("causative", "potential or passive", "negative")),
    CorpusRow("する", "せさせられない", "vs", listOf("causative", "potential or passive", "negative")),
)

private fun category12Chunk2(): List<CorpusRow> = listOf(
    CorpusRow("する", "しまして", "vs", listOf("-ます", "-て")),
    CorpusRow("する", "すれば", "vs", listOf("-ば")),
    CorpusRow("する", "すりゃ", "vs", listOf("-ば", "-ゃ")),
    CorpusRow("する", "しちゃ", "vs", listOf("-ちゃ")),
    CorpusRow("する", "しちゃう", "vs", listOf("-ちゃう")),
    CorpusRow("する", "しちまう", "vs", listOf("-ちまう")),
    CorpusRow("する", "しなさい", "vs", listOf("-なさい")),
    CorpusRow("する", "しそう", "vs", listOf("-そう")),
    CorpusRow("する", "しさう", "vs", listOf("-そう")),
    CorpusRow("する", "しすぎる", "vs", listOf("-すぎる")),
    CorpusRow("する", "し過ぎる", "vs", listOf("-過ぎる")),
    CorpusRow("する", "したい", "vs", listOf("-たい")),
    CorpusRow("する", "したがる", "vs", listOf("-たい", "-がる")),
    CorpusRow("する", "したら", "vs", listOf("-たら")),
    CorpusRow("する", "したり", "vs", listOf("-たり")),
    CorpusRow("する", "せず", "vs", listOf("-ず")),
    CorpusRow("する", "せぬ", "vs", listOf("-ぬ")),
    CorpusRow("する", "せん", "vs", listOf("-ん")),
    CorpusRow("する", "せんかった", "vs", listOf("-ん", "-た")),
    CorpusRow("する", "せんばかり", "vs", listOf("-んばかり")),
    CorpusRow("する", "せんとする", "vs", listOf("-んとする")),
    CorpusRow("する", "せざる", "vs", listOf("-ざる")),
    CorpusRow("する", "せねば", "vs", listOf("-ねば")),
    CorpusRow("する", "せにゃ", "vs", listOf("-ねば", "-ゃ")),
    CorpusRow("する", "し", "vs", listOf("continuative")),
    CorpusRow("する", "しましょう", "vs", listOf("-ます", "volitional")),
    CorpusRow("する", "しませう", "vs", listOf("-ます", "volitional")),
    CorpusRow("する", "しましょっか", "vs", listOf("-ます", "volitional slang")),
    CorpusRow("する", "しよう", "vs", listOf("volitional")),
    CorpusRow("する", "しやう", "vs", listOf("volitional")),
    CorpusRow("する", "しよっか", "vs", listOf("volitional slang")),
    CorpusRow("する", "するまい", "vs", listOf("-まい")),
    CorpusRow("する", "しまい", "vs", listOf("-まい")),
    CorpusRow("する", "しなきゃ", "vs", listOf("negative", "-ば", "-ゃ")),
    CorpusRow("する", "しておく", "vs", listOf("-て", "-おく")),
    CorpusRow("する", "しとく", "vs", listOf("-て", "-おく")),
    CorpusRow("する", "しないでおく", "vs", listOf("negative", "-おく")),
    CorpusRow("する", "しないどく", "vs", listOf("negative", "-おく")),
    CorpusRow("する", "している", "vs", listOf("-て", "-いる")),
    CorpusRow("する", "してゐる", "vs", listOf("-て", "-いる")),
    CorpusRow("する", "しておる", "vs", listOf("-て", "-いる")),
    CorpusRow("する", "してる", "vs", listOf("-て", "-いる")),
    CorpusRow("する", "しとる", "vs", listOf("-て", "-いる")),
    CorpusRow("する", "してしまう", "vs", listOf("-て", "-しまう")),
    CorpusRow("する", "しやがる", "vs", listOf("-やがる")),
    CorpusRow("する", "しやがって", "vs", listOf("-やがる", "-て")),
    CorpusRow("する", "しやがった", "vs", listOf("-やがる", "-た")),
    CorpusRow("する", "しやがれ", "vs", listOf("-やがる", "imperative")),
    CorpusRow("する", "しますまい", "vs", listOf("-ます", "-まい")),
    CorpusRow("する", "しましたら", "vs", listOf("-ます", "-たら")),
)

private fun category12Chunk3(): List<CorpusRow> = listOf(
    CorpusRow("する", "しますれば", "vs", listOf("-ます", "-ば")),
    CorpusRow("する", "しませんかった", "vs", listOf("-ます", "negative", "-た")),
    CorpusRow("来る", "来る", "vk", listOf()),
    CorpusRow("来る", "来ます", "vk", listOf("-ます")),
    CorpusRow("来る", "来た", "vk", listOf("-た")),
    CorpusRow("来る", "来ました", "vk", listOf("-ます", "-た")),
    CorpusRow("来る", "来て", "vk", listOf("-て")),
    CorpusRow("来る", "来られる", "vk", listOf("potential or passive")),
    CorpusRow("来る", "来られる", "vk", listOf("potential or passive")),
    CorpusRow("来る", "来させる", "vk", listOf("causative")),
    CorpusRow("来る", "来さす", "vk", listOf("short causative")),
    CorpusRow("来る", "来さします", "vk", listOf("short causative", "-ます")),
    CorpusRow("来る", "来させられる", "vk", listOf("causative", "potential or passive")),
    CorpusRow("来る", "来い", "vk", listOf("imperative")),
    CorpusRow("来る", "来ない", "vk", listOf("negative")),
    CorpusRow("来る", "来ません", "vk", listOf("-ます", "negative")),
    CorpusRow("来る", "来なかった", "vk", listOf("negative", "-た")),
    CorpusRow("来る", "来ませんでした", "vk", listOf("-ます", "negative", "-た")),
    CorpusRow("来る", "来なくて", "vk", listOf("negative", "-て")),
    CorpusRow("来る", "来られない", "vk", listOf("potential or passive", "negative")),
    CorpusRow("来る", "来られない", "vk", listOf("potential or passive", "negative")),
    CorpusRow("来る", "来させない", "vk", listOf("causative", "negative")),
    CorpusRow("来る", "来ささない", "vk", listOf("short causative", "negative")),
    CorpusRow("来る", "来させられない", "vk", listOf("causative", "potential or passive", "negative")),
    CorpusRow("来る", "来まして", "vk", listOf("-ます", "-て")),
    CorpusRow("来る", "来れば", "vk", listOf("-ば")),
    CorpusRow("来る", "来りゃ", "vk", listOf("-ば", "-ゃ")),
    CorpusRow("来る", "来ちゃ", "vk", listOf("-ちゃ")),
    CorpusRow("来る", "来ちゃう", "vk", listOf("-ちゃう")),
    CorpusRow("来る", "来ちまう", "vk", listOf("-ちまう")),
    CorpusRow("来る", "来なさい", "vk", listOf("-なさい")),
    CorpusRow("来る", "来そう", "vk", listOf("-そう")),
    CorpusRow("来る", "来さう", "vk", listOf("-そう")),
    CorpusRow("来る", "来すぎる", "vk", listOf("-すぎる")),
    CorpusRow("来る", "来過ぎる", "vk", listOf("-過ぎる")),
    CorpusRow("来る", "来たい", "vk", listOf("-たい")),
    CorpusRow("来る", "来たがる", "vk", listOf("-たい", "-がる")),
    CorpusRow("来る", "来たら", "vk", listOf("-たら")),
    CorpusRow("来る", "来たり", "vk", listOf("-たり")),
    CorpusRow("来る", "来ず", "vk", listOf("-ず")),
    CorpusRow("来る", "来ぬ", "vk", listOf("-ぬ")),
    CorpusRow("来る", "来ん", "vk", listOf("-ん")),
    CorpusRow("来る", "来んかった", "vk", listOf("-ん", "-た")),
    CorpusRow("来る", "来んばかり", "vk", listOf("-んばかり")),
    CorpusRow("来る", "来んとする", "vk", listOf("-んとする")),
    CorpusRow("来る", "来ざる", "vk", listOf("-ざる")),
    CorpusRow("来る", "来ねば", "vk", listOf("-ねば")),
    CorpusRow("来る", "来にゃ", "vk", listOf("-ねば", "-ゃ")),
    CorpusRow("来る", "来", "vk", listOf("continuative")),
    CorpusRow("来る", "来ましょう", "vk", listOf("-ます", "volitional")),
)

private fun category12Chunk4(): List<CorpusRow> = listOf(
    CorpusRow("来る", "来ませう", "vk", listOf("-ます", "volitional")),
    CorpusRow("来る", "来ましょっか", "vk", listOf("-ます", "volitional slang")),
    CorpusRow("来る", "来よう", "vk", listOf("volitional")),
    CorpusRow("来る", "来やう", "vk", listOf("volitional")),
    CorpusRow("来る", "来よっか", "vk", listOf("volitional slang")),
    CorpusRow("来る", "来るまい", "vk", listOf("-まい")),
    CorpusRow("来る", "来まい", "vk", listOf("-まい")),
    CorpusRow("来る", "来ておく", "vk", listOf("-て", "-おく")),
    CorpusRow("来る", "来とく", "vk", listOf("-て", "-おく")),
    CorpusRow("来る", "来ないでおく", "vk", listOf("negative", "-おく")),
    CorpusRow("来る", "来ないどく", "vk", listOf("negative", "-おく")),
    CorpusRow("来る", "来ている", "vk", listOf("-て", "-いる")),
    CorpusRow("来る", "来てゐる", "vk", listOf("-て", "-いる")),
    CorpusRow("来る", "来ておる", "vk", listOf("-て", "-いる")),
    CorpusRow("来る", "来てる", "vk", listOf("-て", "-いる")),
    CorpusRow("来る", "来とる", "vk", listOf("-て", "-いる")),
    CorpusRow("来る", "来てしまう", "vk", listOf("-て", "-しまう")),
    CorpusRow("来る", "来ますまい", "vk", listOf("-ます", "-まい")),
    CorpusRow("来る", "来ましたら", "vk", listOf("-ます", "-たら")),
    CorpusRow("来る", "来ますれば", "vk", listOf("-ます", "-ば")),
    CorpusRow("来る", "来ませんかった", "vk", listOf("-ます", "negative", "-た")),
    CorpusRow("來る", "來る", "vk", listOf()),
    CorpusRow("來る", "來ます", "vk", listOf("-ます")),
    CorpusRow("來る", "來た", "vk", listOf("-た")),
    CorpusRow("來る", "來ました", "vk", listOf("-ます", "-た")),
    CorpusRow("來る", "來て", "vk", listOf("-て")),
    CorpusRow("來る", "來られる", "vk", listOf("potential or passive")),
    CorpusRow("來る", "來られる", "vk", listOf("potential or passive")),
    CorpusRow("來る", "來させる", "vk", listOf("causative")),
    CorpusRow("來る", "來さす", "vk", listOf("short causative")),
    CorpusRow("來る", "來さします", "vk", listOf("short causative", "-ます")),
    CorpusRow("來る", "來させられる", "vk", listOf("causative", "potential or passive")),
    CorpusRow("來る", "來い", "vk", listOf("imperative")),
    CorpusRow("來る", "來ない", "vk", listOf("negative")),
    CorpusRow("來る", "來ません", "vk", listOf("-ます", "negative")),
    CorpusRow("來る", "來なかった", "vk", listOf("negative", "-た")),
    CorpusRow("來る", "來ませんでした", "vk", listOf("-ます", "negative", "-た")),
    CorpusRow("來る", "來なくて", "vk", listOf("negative", "-て")),
    CorpusRow("來る", "來られない", "vk", listOf("potential or passive", "negative")),
    CorpusRow("來る", "來られない", "vk", listOf("potential or passive", "negative")),
    CorpusRow("來る", "來させない", "vk", listOf("causative", "negative")),
    CorpusRow("來る", "來ささない", "vk", listOf("short causative", "negative")),
    CorpusRow("來る", "來させられない", "vk", listOf("causative", "potential or passive", "negative")),
    CorpusRow("來る", "來まして", "vk", listOf("-ます", "-て")),
    CorpusRow("來る", "來れば", "vk", listOf("-ば")),
    CorpusRow("來る", "來りゃ", "vk", listOf("-ば", "-ゃ")),
    CorpusRow("來る", "來ちゃ", "vk", listOf("-ちゃ")),
    CorpusRow("來る", "來ちゃう", "vk", listOf("-ちゃう")),
    CorpusRow("來る", "來ちまう", "vk", listOf("-ちまう")),
    CorpusRow("來る", "來なさい", "vk", listOf("-なさい")),
)

private fun category12Chunk5(): List<CorpusRow> = listOf(
    CorpusRow("來る", "來そう", "vk", listOf("-そう")),
    CorpusRow("來る", "來さう", "vk", listOf("-そう")),
    CorpusRow("來る", "來すぎる", "vk", listOf("-すぎる")),
    CorpusRow("來る", "來過ぎる", "vk", listOf("-過ぎる")),
    CorpusRow("來る", "來たい", "vk", listOf("-たい")),
    CorpusRow("來る", "來たがる", "vk", listOf("-たい", "-がる")),
    CorpusRow("來る", "來たら", "vk", listOf("-たら")),
    CorpusRow("來る", "來たり", "vk", listOf("-たり")),
    CorpusRow("來る", "來ず", "vk", listOf("-ず")),
    CorpusRow("來る", "來ぬ", "vk", listOf("-ぬ")),
    CorpusRow("來る", "來ん", "vk", listOf("-ん")),
    CorpusRow("來る", "來んかった", "vk", listOf("-ん", "-た")),
    CorpusRow("來る", "來んばかり", "vk", listOf("-んばかり")),
    CorpusRow("來る", "來んとする", "vk", listOf("-んとする")),
    CorpusRow("來る", "來ざる", "vk", listOf("-ざる")),
    CorpusRow("來る", "來ねば", "vk", listOf("-ねば")),
    CorpusRow("來る", "來にゃ", "vk", listOf("-ねば", "-ゃ")),
    CorpusRow("來る", "來", "vk", listOf("continuative")),
    CorpusRow("來る", "來ましょう", "vk", listOf("-ます", "volitional")),
    CorpusRow("來る", "來ませう", "vk", listOf("-ます", "volitional")),
    CorpusRow("來る", "來ましょっか", "vk", listOf("-ます", "volitional slang")),
    CorpusRow("來る", "來よう", "vk", listOf("volitional")),
    CorpusRow("來る", "來やう", "vk", listOf("volitional")),
    CorpusRow("來る", "來よっか", "vk", listOf("volitional slang")),
    CorpusRow("來る", "來るまい", "vk", listOf("-まい")),
    CorpusRow("來る", "來とく", "vk", listOf("-て", "-おく")),
    CorpusRow("來る", "來ておく", "vk", listOf("-て", "-おく")),
    CorpusRow("來る", "來とく", "vk", listOf("-て", "-おく")),
    CorpusRow("來る", "來ないでおく", "vk", listOf("negative", "-おく")),
    CorpusRow("來る", "來ないどく", "vk", listOf("negative", "-おく")),
    CorpusRow("來る", "來ている", "vk", listOf("-て", "-いる")),
    CorpusRow("來る", "來てゐる", "vk", listOf("-て", "-いる")),
    CorpusRow("來る", "來ておる", "vk", listOf("-て", "-いる")),
    CorpusRow("來る", "來てる", "vk", listOf("-て", "-いる")),
    CorpusRow("來る", "來とる", "vk", listOf("-て", "-いる")),
    CorpusRow("來る", "來てしまう", "vk", listOf("-て", "-しまう")),
    CorpusRow("來る", "來ますまい", "vk", listOf("-ます", "-まい")),
    CorpusRow("來る", "來ましたら", "vk", listOf("-ます", "-たら")),
    CorpusRow("來る", "來ますれば", "vk", listOf("-ます", "-ば")),
    CorpusRow("來る", "來ませんかった", "vk", listOf("-ます", "negative", "-た")),
    CorpusRow("くる", "くる", "vk", listOf()),
    CorpusRow("くる", "きます", "vk", listOf("-ます")),
    CorpusRow("くる", "きた", "vk", listOf("-た")),
    CorpusRow("くる", "きました", "vk", listOf("-ます", "-た")),
    CorpusRow("くる", "きて", "vk", listOf("-て")),
    CorpusRow("くる", "こられる", "vk", listOf("potential or passive")),
    CorpusRow("くる", "こられる", "vk", listOf("potential or passive")),
    CorpusRow("くる", "こさせる", "vk", listOf("causative")),
    CorpusRow("くる", "こさす", "vk", listOf("short causative")),
    CorpusRow("くる", "こさします", "vk", listOf("short causative", "-ます")),
)

private fun category12Chunk6(): List<CorpusRow> = listOf(
    CorpusRow("くる", "こさせられる", "vk", listOf("causative", "potential or passive")),
    CorpusRow("くる", "こい", "vk", listOf("imperative")),
    CorpusRow("くる", "こない", "vk", listOf("negative")),
    CorpusRow("くる", "きません", "vk", listOf("-ます", "negative")),
    CorpusRow("くる", "こなかった", "vk", listOf("negative", "-た")),
    CorpusRow("くる", "きませんでした", "vk", listOf("-ます", "negative", "-た")),
    CorpusRow("くる", "こなくて", "vk", listOf("negative", "-て")),
    CorpusRow("くる", "こられない", "vk", listOf("potential or passive", "negative")),
    CorpusRow("くる", "こられない", "vk", listOf("potential or passive", "negative")),
    CorpusRow("くる", "こさせない", "vk", listOf("causative", "negative")),
    CorpusRow("くる", "こささない", "vk", listOf("short causative", "negative")),
    CorpusRow("くる", "こさせられない", "vk", listOf("causative", "potential or passive", "negative")),
    CorpusRow("くる", "きまして", "vk", listOf("-ます", "-て")),
    CorpusRow("くる", "くれば", "vk", listOf("-ば")),
    CorpusRow("くる", "くりゃ", "vk", listOf("-ば", "-ゃ")),
    CorpusRow("くる", "きちゃ", "vk", listOf("-ちゃ")),
    CorpusRow("くる", "きちゃう", "vk", listOf("-ちゃう")),
    CorpusRow("くる", "きちまう", "vk", listOf("-ちまう")),
    CorpusRow("くる", "きなさい", "vk", listOf("-なさい")),
    CorpusRow("くる", "きそう", "vk", listOf("-そう")),
    CorpusRow("くる", "きさう", "vk", listOf("-そう")),
    CorpusRow("くる", "きすぎる", "vk", listOf("-すぎる")),
    CorpusRow("くる", "き過ぎる", "vk", listOf("-過ぎる")),
    CorpusRow("くる", "きたい", "vk", listOf("-たい")),
    CorpusRow("くる", "きたがる", "vk", listOf("-たい", "-がる")),
    CorpusRow("くる", "きたら", "vk", listOf("-たら")),
    CorpusRow("くる", "きたり", "vk", listOf("-たり")),
    CorpusRow("くる", "こず", "vk", listOf("-ず")),
    CorpusRow("くる", "こぬ", "vk", listOf("-ぬ")),
    CorpusRow("くる", "こん", "vk", listOf("-ん")),
    CorpusRow("くる", "こんかった", "vk", listOf("-ん", "-た")),
    CorpusRow("くる", "こんばかり", "vk", listOf("-んばかり")),
    CorpusRow("くる", "こんとする", "vk", listOf("-んとする")),
    CorpusRow("くる", "こざる", "vk", listOf("-ざる")),
    CorpusRow("くる", "こねば", "vk", listOf("-ねば")),
    CorpusRow("くる", "こにゃ", "vk", listOf("-ねば", "-ゃ")),
    CorpusRow("くる", "き", "vk", listOf("continuative")),
    CorpusRow("くる", "きましょう", "vk", listOf("-ます", "volitional")),
    CorpusRow("くる", "きませう", "vk", listOf("-ます", "volitional")),
    CorpusRow("くる", "きましょっか", "vk", listOf("-ます", "volitional slang")),
    CorpusRow("くる", "こよう", "vk", listOf("volitional")),
    CorpusRow("くる", "こやう", "vk", listOf("volitional")),
    CorpusRow("くる", "こよっか", "vk", listOf("volitional slang")),
    CorpusRow("くる", "くるまい", "vk", listOf("-まい")),
    CorpusRow("くる", "こまい", "vk", listOf("-まい")),
    CorpusRow("くる", "きておく", "vk", listOf("-て", "-おく")),
    CorpusRow("くる", "きとく", "vk", listOf("-て", "-おく")),
    CorpusRow("くる", "こないでおく", "vk", listOf("negative", "-おく")),
    CorpusRow("くる", "こないどく", "vk", listOf("negative", "-おく")),
    CorpusRow("くる", "きている", "vk", listOf("-て", "-いる")),
)

private fun category12Chunk7(): List<CorpusRow> = listOf(
    CorpusRow("くる", "きてゐる", "vk", listOf("-て", "-いる")),
    CorpusRow("くる", "きておる", "vk", listOf("-て", "-いる")),
    CorpusRow("くる", "きてる", "vk", listOf("-て", "-いる")),
    CorpusRow("くる", "きとる", "vk", listOf("-て", "-いる")),
    CorpusRow("くる", "きてしまう", "vk", listOf("-て", "-しまう")),
    CorpusRow("くる", "きやがる", "vk", listOf("-やがる")),
    CorpusRow("くる", "きやがって", "vk", listOf("-やがる", "-て")),
    CorpusRow("くる", "きやがった", "vk", listOf("-やがる", "-た")),
    CorpusRow("くる", "きやがれ", "vk", listOf("-やがる", "imperative")),
    CorpusRow("くる", "きますまい", "vk", listOf("-ます", "-まい")),
    CorpusRow("くる", "きましたら", "vk", listOf("-ます", "-たら")),
    CorpusRow("くる", "きますれば", "vk", listOf("-ます", "-ば")),
    CorpusRow("くる", "きませんかった", "vk", listOf("-ます", "negative", "-た")),
)

private fun category12(): CorpusCategory = CorpusCategory(
    category = "irregular verbs",
    valid = true,
    rows = category12Chunk0() + category12Chunk1() + category12Chunk2() + category12Chunk3() + category12Chunk4() + category12Chunk5() + category12Chunk6() + category12Chunk7(),
)

private fun category13Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("論ずる", "論ずる", "vz", listOf()),
    CorpusRow("論ずる", "論じます", "vz", listOf("-ます")),
    CorpusRow("論ずる", "論じた", "vz", listOf("-た")),
    CorpusRow("論ずる", "論じました", "vz", listOf("-ます", "-た")),
    CorpusRow("論ずる", "論じて", "vz", listOf("-て")),
    CorpusRow("論ずる", "論ぜられる", "vz", listOf("potential or passive")),
    CorpusRow("論ずる", "論ざれる", "vz", listOf("potential or passive")),
    CorpusRow("論ずる", "論じされる", "vz", listOf("passive")),
    CorpusRow("論ずる", "論ぜされる", "vz", listOf("passive")),
    CorpusRow("論ずる", "論じさせる", "vz", listOf("causative")),
    CorpusRow("論ずる", "論ぜさせる", "vz", listOf("causative")),
    CorpusRow("論ずる", "論じさす", "vz", listOf("short causative")),
    CorpusRow("論ずる", "論ぜさす", "vz", listOf("short causative")),
    CorpusRow("論ずる", "論じさします", "vz", listOf("short causative", "-ます")),
    CorpusRow("論ずる", "論ぜさします", "vz", listOf("short causative", "-ます")),
    CorpusRow("論ずる", "論じさせられる", "vz", listOf("causative", "potential or passive")),
    CorpusRow("論ずる", "論ぜさせられる", "vz", listOf("causative", "potential or passive")),
    CorpusRow("論ずる", "論じろ", "vz", listOf("imperative")),
    CorpusRow("論ずる", "論じない", "vz", listOf("negative")),
    CorpusRow("論ずる", "論じません", "vz", listOf("-ます", "negative")),
    CorpusRow("論ずる", "論じなかった", "vz", listOf("negative", "-た")),
    CorpusRow("論ずる", "論じませんでした", "vz", listOf("-ます", "negative", "-た")),
    CorpusRow("論ずる", "論じなくて", "vz", listOf("negative", "-て")),
    CorpusRow("論ずる", "論ぜられない", "vz", listOf("potential or passive", "negative")),
    CorpusRow("論ずる", "論じされない", "vz", listOf("passive", "negative")),
    CorpusRow("論ずる", "論ぜされない", "vz", listOf("passive", "negative")),
    CorpusRow("論ずる", "論じさせない", "vz", listOf("causative", "negative")),
    CorpusRow("論ずる", "論ぜさせない", "vz", listOf("causative", "negative")),
    CorpusRow("論ずる", "論じささない", "vz", listOf("short causative", "negative")),
    CorpusRow("論ずる", "論ぜささない", "vz", listOf("short causative", "negative")),
    CorpusRow("論ずる", "論じさせられない", "vz", listOf("causative", "potential or passive", "negative")),
    CorpusRow("論ずる", "論ぜさせられない", "vz", listOf("causative", "potential or passive", "negative")),
    CorpusRow("論ずる", "論じまして", "vz", listOf("-ます", "-て")),
    CorpusRow("論ずる", "論ずれば", "vz", listOf("-ば")),
    CorpusRow("論ずる", "論ずりゃ", "vz", listOf("-ば", "-ゃ")),
    CorpusRow("論ずる", "論じちゃ", "vz", listOf("-ちゃ")),
    CorpusRow("論ずる", "論じちゃう", "vz", listOf("-ちゃう")),
    CorpusRow("論ずる", "論じちまう", "vz", listOf("-ちまう")),
    CorpusRow("論ずる", "論じなさい", "vz", listOf("-なさい")),
    CorpusRow("論ずる", "論じそう", "vz", listOf("-そう")),
    CorpusRow("論ずる", "論じさう", "vz", listOf("-そう")),
    CorpusRow("論ずる", "論じすぎる", "vz", listOf("-すぎる")),
    CorpusRow("論ずる", "論じ過ぎる", "vz", listOf("-過ぎる")),
    CorpusRow("論ずる", "論じたい", "vz", listOf("-たい")),
    CorpusRow("論ずる", "論じたがる", "vz", listOf("-たい", "-がる")),
    CorpusRow("論ずる", "論じたら", "vz", listOf("-たら")),
    CorpusRow("論ずる", "論じたり", "vz", listOf("-たり")),
    CorpusRow("論ずる", "論ぜず", "vz", listOf("-ず")),
    CorpusRow("論ずる", "論ぜぬ", "vz", listOf("-ぬ")),
    CorpusRow("論ずる", "論ぜん", "vz", listOf("-ん")),
)

private fun category13Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("論ずる", "論ぜんかった", "vz", listOf("-ん", "-た")),
    CorpusRow("論ずる", "論ぜんばかり", "vz", listOf("-んばかり")),
    CorpusRow("論ずる", "論ぜんとする", "vz", listOf("-んとする")),
    CorpusRow("論ずる", "論ぜざる", "vz", listOf("-ざる")),
    CorpusRow("論ずる", "論ぜねば", "vz", listOf("-ねば")),
    CorpusRow("論ずる", "論ぜにゃ", "vz", listOf("-ねば", "-ゃ")),
    CorpusRow("論ずる", "論じましょう", "vz", listOf("-ます", "volitional")),
    CorpusRow("論ずる", "論じませう", "vz", listOf("-ます", "volitional")),
    CorpusRow("論ずる", "論じよう", "vz", listOf("volitional")),
    CorpusRow("論ずる", "論じやう", "vz", listOf("volitional")),
    CorpusRow("論ずる", "論ずるまい", "vz", listOf("-まい")),
    CorpusRow("論ずる", "論じまい", "vz", listOf("-まい")),
    CorpusRow("論ずる", "論じとく", "vz", listOf("-て", "-おく")),
    CorpusRow("論ずる", "論じている", "vz", listOf("-て", "-いる")),
    CorpusRow("論ずる", "論じてゐる", "vz", listOf("-て", "-いる")),
    CorpusRow("論ずる", "論じておる", "vz", listOf("-て", "-いる")),
    CorpusRow("論ずる", "論じてる", "vz", listOf("-て", "-いる")),
    CorpusRow("論ずる", "論じとる", "vz", listOf("-て", "-いる")),
    CorpusRow("論ずる", "論じてしまう", "vz", listOf("-て", "-しまう")),
    CorpusRow("論ずる", "論じやがる", "vz", listOf("-やがる")),
    CorpusRow("論ずる", "論じやがって", "vz", listOf("-やがる", "-て")),
    CorpusRow("論ずる", "論じやがった", "vz", listOf("-やがる", "-た")),
    CorpusRow("論ずる", "論じやがれ", "vz", listOf("-やがる", "imperative")),
)

private fun category13(): CorpusCategory = CorpusCategory(
    category = "-ずる verbs",
    valid = true,
    rows = category13Chunk0() + category13Chunk1(),
)

private fun category14Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("すごい", "すげえ", "adj-i", listOf("-え")),
    CorpusRow("やばい", "やべえ", "adj-i", listOf("-え")),
    CorpusRow("うるさい", "うるせえ", "adj-i", listOf("-え")),
    CorpusRow("ひどい", "ひでえ", "adj-i", listOf("-え")),
    CorpusRow("ない", "ねえ", "adj-i", listOf("-え")),
    CorpusRow("できる", "できねえ", "v1", listOf("negative", "-え")),
    CorpusRow("しんじる", "しんじねえ", "v1", listOf("negative", "-え")),
    CorpusRow("さむい", "さめえ", "adj-i", listOf("-え")),
    CorpusRow("さむい", "さみい", "adj-i", listOf("-え")),
    CorpusRow("あつい", "あちぇえ", "adj-i", listOf("-え")),
    CorpusRow("あつい", "あちい", "adj-i", listOf("-え")),
    CorpusRow("やすい", "やせえ", "adj-i", listOf("-え")),
    CorpusRow("たかい", "たけえ", "adj-i", listOf("-え")),
    CorpusRow("かわいい", "かわええ", "adj-i", listOf("-え")),
    CorpusRow("つよい", "ついぇえ", "adj-i", listOf("-え")),
    CorpusRow("こわい", "こうぇえ", "adj-i", listOf("-え")),
    CorpusRow("みじかい", "みじけえ", "adj-i", listOf("-え")),
    CorpusRow("ながい", "なげえ", "adj-i", listOf("-え")),
    CorpusRow("くさい", "くせえ", "adj-i", listOf("-え")),
    CorpusRow("うまい", "うめえ", "adj-i", listOf("-え")),
    CorpusRow("でかい", "でけえ", "adj-i", listOf("-え")),
    CorpusRow("まずい", "まっぜえ", "adj-i", listOf("-え")),
    CorpusRow("ちっちゃい", "ちっちぇえ", "adj-i", listOf("-え")),
    CorpusRow("あかい", "あけえ", "adj-i", listOf("-え")),
    CorpusRow("こわい", "こええ", "adj-i", listOf("-え")),
    CorpusRow("つよい", "つええ", "adj-i", listOf("-え")),
    CorpusRow("すごい", "すげぇ", "adj-i", listOf("-え")),
    CorpusRow("やばい", "やべぇ", "adj-i", listOf("-え")),
    CorpusRow("うるさい", "うるせぇ", "adj-i", listOf("-え")),
    CorpusRow("ひどい", "ひでぇ", "adj-i", listOf("-え")),
    CorpusRow("ない", "ねぇ", "adj-i", listOf("-え")),
    CorpusRow("できる", "できねぇ", "v1", listOf("negative", "-え")),
    CorpusRow("しんじる", "しんじねぇ", "v1", listOf("negative", "-え")),
    CorpusRow("さむい", "さめぇ", "adj-i", listOf("-え")),
    CorpusRow("さむい", "さみぃ", "adj-i", listOf("-え")),
    CorpusRow("あつい", "あちぃ", "adj-i", listOf("-え")),
    CorpusRow("やすい", "やせぇ", "adj-i", listOf("-え")),
    CorpusRow("たかい", "たけぇ", "adj-i", listOf("-え")),
    CorpusRow("みじかい", "みじけぇ", "adj-i", listOf("-え")),
    CorpusRow("ながい", "なげぇ", "adj-i", listOf("-え")),
    CorpusRow("くさい", "くせぇ", "adj-i", listOf("-え")),
    CorpusRow("うまい", "うめぇ", "adj-i", listOf("-え")),
    CorpusRow("でかい", "でけぇ", "adj-i", listOf("-え")),
    CorpusRow("まずい", "まっぜぇ", "adj-i", listOf("-え")),
    CorpusRow("あかい", "あけぇ", "adj-i", listOf("-え")),
)

private fun category14(): CorpusCategory = CorpusCategory(
    category = "-え verbs and adjectives",
    valid = true,
    rows = category14Chunk0(),
)

private fun category15Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("わかる", "わかんねえ", "v5", listOf("negative", "n-slang", "-え")),
    CorpusRow("する", "すんな", "vs", listOf("imperative negative slang")),
    CorpusRow("やる", "やんなさい", "v5", listOf("-なさい", "n-slang")),
    CorpusRow("食べる", "食べらんない", "v1", listOf("potential or passive", "negative", "n-slang")),
    CorpusRow("やる", "やんなきゃ", "v5", listOf("negative", "n-slang", "-ば", "-ゃ")),
    CorpusRow("くれる", "くんなきゃ", "v1", listOf("negative", "-ば", "-ゃ", "n-slang")),
)

private fun category15(): CorpusCategory = CorpusCategory(
    category = "n-slang",
    valid = true,
    rows = category15Chunk0(),
)

private fun category16Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("する", "すます", "vs", null),
    CorpusRow("する", "すた", "vs", null),
    CorpusRow("する", "すました", "vs", null),
    CorpusRow("する", "すて", "vs", null),
    CorpusRow("する", "すれる", "vs", null),
    CorpusRow("する", "すせる", "vs", null),
    CorpusRow("する", "すせられる", "vs", null),
    CorpusRow("する", "すろ", "vs", null),
    CorpusRow("する", "すない", "vs", null),
    CorpusRow("する", "すません", "vs", null),
    CorpusRow("する", "すなかった", "vs", null),
    CorpusRow("する", "すませんでした", "vs", null),
    CorpusRow("する", "すなくて", "vs", null),
    CorpusRow("する", "すれない", "vs", null),
    CorpusRow("する", "すせない", "vs", null),
    CorpusRow("する", "すせられない", "vs", null),
    CorpusRow("くる", "くます", "vk", null),
    CorpusRow("くる", "くた", "vk", null),
    CorpusRow("くる", "くました", "vk", null),
    CorpusRow("くる", "くて", "vk", null),
    CorpusRow("くる", "くられる", "vk", null),
    CorpusRow("くる", "くられる", "vk", null),
    CorpusRow("くる", "くさせる", "vk", null),
    CorpusRow("くる", "くさせられる", "vk", null),
    CorpusRow("くる", "くい", "vk", null),
    CorpusRow("くる", "くない", "vk", null),
    CorpusRow("くる", "くません", "vk", null),
    CorpusRow("くる", "くなかった", "vk", null),
    CorpusRow("くる", "くませんでした", "vk", null),
    CorpusRow("くる", "くなくて", "vk", null),
    CorpusRow("くる", "くられない", "vk", null),
    CorpusRow("くる", "くられない", "vk", null),
    CorpusRow("くる", "くさせない", "vk", null),
    CorpusRow("くる", "くさせられない", "vk", null),
)

private fun category16(): CorpusCategory = CorpusCategory(
    category = "irregular verbs",
    valid = false,
    rows = category16Chunk0(),
)

private fun category17Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("のたまう", "のたもうて", "v5", listOf("-て")),
    CorpusRow("のたまう", "のたもうた", "v5", listOf("-た")),
    CorpusRow("のたまう", "のたもうたら", "v5", listOf("-たら")),
    CorpusRow("のたまう", "のたもうたり", "v5", listOf("-たり")),
    CorpusRow("宣う", "宣うて", "v5", listOf("-て")),
    CorpusRow("宣う", "宣うた", "v5", listOf("-た")),
    CorpusRow("宣う", "宣うたら", "v5", listOf("-たら")),
    CorpusRow("宣う", "宣うたり", "v5", listOf("-たり")),
    CorpusRow("曰う", "曰うて", "v5", listOf("-て")),
    CorpusRow("曰う", "曰うた", "v5", listOf("-た")),
    CorpusRow("曰う", "曰うたら", "v5", listOf("-たら")),
    CorpusRow("曰う", "曰うたり", "v5", listOf("-たり")),
    CorpusRow("たまう", "たもうて", "v5", listOf("-て")),
    CorpusRow("たまう", "たもうた", "v5", listOf("-た")),
    CorpusRow("たまう", "たもうたら", "v5", listOf("-たら")),
    CorpusRow("たまう", "たもうたり", "v5", listOf("-たり")),
    CorpusRow("給う", "給うて", "v5", listOf("-て")),
    CorpusRow("給う", "給うた", "v5", listOf("-た")),
    CorpusRow("給う", "給うたら", "v5", listOf("-たら")),
    CorpusRow("給う", "給うたり", "v5", listOf("-たり")),
    CorpusRow("賜う", "賜うて", "v5", listOf("-て")),
    CorpusRow("賜う", "賜うた", "v5", listOf("-た")),
    CorpusRow("賜う", "賜うたら", "v5", listOf("-たら")),
    CorpusRow("賜う", "賜うたり", "v5", listOf("-たり")),
    CorpusRow("たゆたう", "たゆとうて", "v5", listOf("-て")),
    CorpusRow("たゆたう", "たゆとうた", "v5", listOf("-た")),
    CorpusRow("たゆたう", "たゆとうたら", "v5", listOf("-たら")),
    CorpusRow("たゆたう", "たゆとうたり", "v5", listOf("-たり")),
    CorpusRow("こう", "こうて", "v5", listOf("-て")),
    CorpusRow("とう", "とうて", "v5", listOf("-て")),
    CorpusRow("請う", "請うて", "v5", listOf("-て")),
    CorpusRow("乞う", "乞うて", "v5", listOf("-て")),
    CorpusRow("恋う", "恋うて", "v5", listOf("-て")),
    CorpusRow("問う", "問うて", "v5", listOf("-て")),
    CorpusRow("訪う", "訪うて", "v5", listOf("-て")),
    CorpusRow("こう", "こうた", "v5", listOf("-た")),
    CorpusRow("とう", "とうた", "v5", listOf("-た")),
    CorpusRow("請う", "請うた", "v5", listOf("-た")),
    CorpusRow("乞う", "乞うた", "v5", listOf("-た")),
    CorpusRow("恋う", "恋うた", "v5", listOf("-た")),
    CorpusRow("問う", "問うた", "v5", listOf("-た")),
    CorpusRow("訪う", "訪うた", "v5", listOf("-た")),
    CorpusRow("こう", "こうたら", "v5", listOf("-たら")),
    CorpusRow("とう", "とうたら", "v5", listOf("-たら")),
    CorpusRow("請う", "請うたら", "v5", listOf("-たら")),
    CorpusRow("乞う", "乞うたら", "v5", listOf("-たら")),
    CorpusRow("恋う", "恋うたら", "v5", listOf("-たら")),
    CorpusRow("問う", "問うたら", "v5", listOf("-たら")),
    CorpusRow("訪う", "訪うたら", "v5", listOf("-たら")),
    CorpusRow("こう", "こうたり", "v5", listOf("-たり")),
)

private fun category17Chunk1(): List<CorpusRow> = listOf(
    CorpusRow("とう", "とうたり", "v5", listOf("-たり")),
    CorpusRow("請う", "請うたり", "v5", listOf("-たり")),
    CorpusRow("乞う", "乞うたり", "v5", listOf("-たり")),
    CorpusRow("恋う", "恋うたり", "v5", listOf("-たり")),
    CorpusRow("問う", "問うたり", "v5", listOf("-たり")),
    CorpusRow("訪う", "訪うたり", "v5", listOf("-たり")),
)

private fun category17(): CorpusCategory = CorpusCategory(
    category = "uncommon irregular verbs",
    valid = true,
    rows = category17Chunk0() + category17Chunk1(),
)

private fun category18Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("抱き抱える", "抱き抱えていなければ", "v1", listOf("-て", "-いる", "negative", "-ば")),
    CorpusRow("抱きかかえる", "抱きかかえていなければ", "v1", listOf("-て", "-いる", "negative", "-ば")),
    CorpusRow("打ち込む", "打ち込んでいませんでした", "v5", listOf("-て", "-いる", "-ます", "negative", "-た")),
    CorpusRow("食べる", "食べさせられたくなかった", "v1", listOf("causative", "potential or passive", "-たい", "negative", "-た")),
    CorpusRow("食べる", "食べんとしませんかった", "v1", listOf("-んとする", "-ます", "negative", "-た")),
    CorpusRow("食べる", "食べないどきたくありません", "v1", listOf("negative", "-おく", "-たい", "-ます", "negative")),
)

private fun category18(): CorpusCategory = CorpusCategory(
    category = "combinations",
    valid = true,
    rows = category18Chunk0(),
)

private fun category19Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("食べる", "食べないでいる", "v1", listOf("negative", "-いる")),
    CorpusRow("食べる", "食べないでゐる", "v1", listOf("negative", "-いる")),
)

private fun category19(): CorpusCategory = CorpusCategory(
    category = "ないでいる",
    valid = true,
    rows = category19Chunk0(),
)

private fun category20Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("かわいい", "かわいげ", "adj-i", listOf("-げ")),
    CorpusRow("可愛い", "可愛げ", "adj-i", listOf("-げ")),
    CorpusRow("可愛い", "可愛気", "adj-i", listOf("-げ")),
)

private fun category20(): CorpusCategory = CorpusCategory(
    category = "kawaii",
    valid = true,
    rows = category20Chunk0(),
)

private fun category21Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("思う", "思ふ", "v5", listOf("-ふ")),
    CorpusRow("思う", "思へば", "v5", listOf("-ば")),
    CorpusRow("思う", "思はず", "v5", listOf("-ず")),
    CorpusRow("思う", "思はぬ", "v5", listOf("-ぬ")),
    CorpusRow("思う", "思はん", "v5", listOf("-ん")),
    CorpusRow("思う", "思はんばかり", "v5", listOf("-んばかり")),
    CorpusRow("思う", "思はんとする", "v5", listOf("-んとする")),
    CorpusRow("思う", "思はむ", "v5", listOf("-む")),
    CorpusRow("思う", "思はざる", "v5", listOf("-ざる")),
    CorpusRow("思う", "思はねば", "v5", listOf("-ねば")),
    CorpusRow("思う", "思はせる", "v5", listOf("causative")),
    CorpusRow("思う", "思はす", "v5", listOf("short causative")),
    CorpusRow("思う", "思へ", "v5", listOf("imperative")),
    CorpusRow("思う", "思ひ", "v5", listOf("continuative")),
    CorpusRow("思う", "思はない", "v5", listOf("negative")),
    CorpusRow("思う", "思はれる", "v5", listOf("passive")),
    CorpusRow("思う", "思ひます", "v5", listOf("-ます")),
    CorpusRow("思う", "思はう", "v5", listOf("volitional")),
)

private fun category21(): CorpusCategory = CorpusCategory(
    category = "historical kana (歴史的仮名遣い)",
    valid = true,
    rows = category21Chunk0(),
)

private fun category22Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("思う", "思はせられたくない", "v5", listOf("causative", "potential or passive", "-たい", "negative")),
    CorpusRow("思う", "思ってしまふ", "v5", listOf("-て", "-しまう", "-ふ")),
    CorpusRow("思う", "思ってしまひました", "v5", listOf("-て", "-しまう", "-ます", "-た")),
    CorpusRow("思う", "思ってしまはう", "v5", listOf("-て", "-しまう", "volitional")),
    CorpusRow("思う", "思ってゐぬ", "v5", listOf("-て", "-いる", "-ぬ")),
)

private fun category22(): CorpusCategory = CorpusCategory(
    category = "historical kana (歴史的仮名遣い) - combinations",
    valid = true,
    rows = category22Chunk0(),
)

private fun category23Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("食べる", "食べて", null, listOf("-て", "-いる", "continuative")),
    CorpusRow("なる", "なりません", null, listOf("-ます", "potential", "-ん")),
    CorpusRow("食べる", "食べさせられる", null, listOf("short causative", "potential", "potential or passive")),
    CorpusRow("食べる", "食べまさない", null, listOf("-ます", "negative")),
    CorpusRow("食べる", "食べましたい", null, listOf("-ます", "-たい")),
    CorpusRow("済ます", "済ません", null, listOf("-ます", "negative")),
    CorpusRow("済ます", "済ましょう", null, listOf("-ます", "volitional")),
)

private fun category23(): CorpusCategory = CorpusCategory(
    category = "incorrect chains",
    valid = false,
    rows = category23Chunk0(),
)

private fun category24Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("食べる", "食べさされる", null, listOf("short causative", "passive")),
    CorpusRow("話す", "話さされる", null, listOf("short causative", "passive")),
    CorpusRow("論ずる", "論じさされる", null, listOf("short causative", "passive")),
    CorpusRow("論ずる", "論ぜさされる", null, listOf("short causative", "passive")),
    CorpusRow("する", "さされる", null, listOf("short causative", "passive")),
    CorpusRow("為る", "為される", null, listOf("short causative", "passive")),
    CorpusRow("くる", "こさされる", null, listOf("short causative", "passive")),
    CorpusRow("来る", "来さされる", null, listOf("short causative", "passive")),
    CorpusRow("來る", "來さされる", null, listOf("short causative", "passive")),
)

private fun category24(): CorpusCategory = CorpusCategory(
    category = "incorrect short causative -> passive chains",
    valid = false,
    rows = category24Chunk0(),
)

private fun category25Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("宜しい", "宜しゅう", null, listOf("-く", "kansai-ben -く")),
    CorpusRow("よろしい", "よろしゅう", null, listOf("-く", "kansai-ben -く")),
    CorpusRow("良い", "良う", null, listOf("-く", "kansai-ben -く")),
    CorpusRow("よい", "よう", null, listOf("-く", "kansai-ben -く")),
)

private fun category25(): CorpusCategory = CorpusCategory(
    category = "-く stem of kansai-ben adjectives",
    valid = true,
    rows = category25Chunk0(),
)

private fun category26Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("よろしい", "よろしゅうて", null, listOf("-て", "kansai-ben adjective -て")),
    CorpusRow("宜しい", "宜しゅうて", null, listOf("-て", "kansai-ben adjective -て")),
    CorpusRow("よい", "ようて", null, listOf("-て", "kansai-ben adjective -て")),
    CorpusRow("良い", "良うて", null, listOf("-て", "kansai-ben adjective -て")),
)

private fun category26(): CorpusCategory = CorpusCategory(
    category = "-て form of kansai-ben adjectives",
    valid = true,
    rows = category26Chunk0(),
)

private fun category27Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("よろしい", "よろしゅうない", null, listOf("negative", "kansai-ben adjective negative")),
    CorpusRow("宜しい", "宜しゅうない", null, listOf("negative", "kansai-ben adjective negative")),
    CorpusRow("よい", "ようない", null, listOf("negative", "kansai-ben adjective negative")),
    CorpusRow("良い", "良うない", null, listOf("negative", "kansai-ben adjective negative")),
)

private fun category27(): CorpusCategory = CorpusCategory(
    category = "Negative form of kansai-ben adjectives",
    valid = true,
    rows = category27Chunk0(),
)

private fun category28Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("食べる", "食べへん", null, listOf("negative", "kansai-ben negative")),
    CorpusRow("食べる", "食べへんかった", null, listOf("negative", "-た", "kansai-ben negative")),
)

private fun category28(): CorpusCategory = CorpusCategory(
    category = "Negative form of kansai-ben verbs",
    valid = true,
    rows = category28Chunk0(),
)

private fun category29Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("買う", "買うて", null, listOf("-て", "kansai-ben -て")),
    CorpusRow("かう", "こうて", null, listOf("-て", "kansai-ben -て")),
    CorpusRow("はう", "ほうて", null, listOf("-て", "kansai-ben -て")),
)

private fun category29(): CorpusCategory = CorpusCategory(
    category = "-て form of kansai-ben verbs",
    valid = true,
    rows = category29Chunk0(),
)

private fun category30Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("買う", "買うた", null, listOf("-た", "kansai-ben -た")),
    CorpusRow("かう", "こうた", null, listOf("-た", "kansai-ben -た")),
    CorpusRow("はう", "ほうた", null, listOf("-た", "kansai-ben -た")),
)

private fun category30(): CorpusCategory = CorpusCategory(
    category = "-た form of kansai-ben terms",
    valid = true,
    rows = category30Chunk0(),
)

private fun category31Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("買う", "買うたら", null, listOf("-たら", "kansai-ben -たら")),
    CorpusRow("かう", "こうたら", null, listOf("-たら", "kansai-ben -たら")),
    CorpusRow("はう", "ほうたら", null, listOf("-たら", "kansai-ben -たら")),
)

private fun category31(): CorpusCategory = CorpusCategory(
    category = "-たら form of kansai-ben terms",
    valid = true,
    rows = category31Chunk0(),
)

private fun category32Chunk0(): List<CorpusRow> = listOf(
    CorpusRow("買う", "買うたり", null, listOf("-たり", "kansai-ben -たり")),
    CorpusRow("かう", "こうたり", null, listOf("-たり", "kansai-ben -たり")),
    CorpusRow("はう", "ほうたり", null, listOf("-たり", "kansai-ben -たり")),
)

private fun category32(): CorpusCategory = CorpusCategory(
    category = "-たり form of kansai-ben terms",
    valid = true,
    rows = category32Chunk0(),
)

val japaneseTransformsCorpus: List<CorpusCategory> = listOf(
    category0(),
    category1(),
    category2(),
    category3(),
    category4(),
    category5(),
    category6(),
    category7(),
    category8(),
    category9(),
    category10(),
    category11(),
    category12(),
    category13(),
    category14(),
    category15(),
    category16(),
    category17(),
    category18(),
    category19(),
    category20(),
    category21(),
    category22(),
    category23(),
    category24(),
    category25(),
    category26(),
    category27(),
    category28(),
    category29(),
    category30(),
    category31(),
    category32(),
)
